- src/Orchard.Web/Modules/Orchard.Recipes/Services/RecipeStepQueue.cs
This happens when trying to delete the recipe directory that isn't empty yet
> #5148: Default recipe error on setup (Milestone: 1.8.x)

- src/Orchard.Web/Modules/Orchard.Taxonomies/Handlers/TermsPartHandler.cs
- src/Orchard.Web/Modules/Orchard.Taxonomies/Services/ITermCountProcessor.cs
- src/Orchard.Web/Modules/Orchard.Taxonomies/Services/TaxonomyService.cs
- src/Orchard.Web/Modules/Orchard.Taxonomies/Services/TermCountProcessor.cs
I think the problem is that the TermsPartHandler triggers the TermCountProcessor as a Task async and the TermCountProcessor used the ContentTypeId as a parameter.
If a ContentItem gets deleted, the TermCountProcessor cannot access it anymore and the Terms won't getting reprocessed which results in a wrong count.
I altered the ITermCountProcessor interface to accept TermPartRecordId's instead of the ContentTypeId and use this id's directly.
I also had to add a call for the ITermCountProcessor in the TermService UpdateTerm method. This is because when you re-publish a ContentItem only the new Terms are available in the PublishedEvent - but also terms from the previous version needed to be processed (Count decreased).
> Fixed #4905: Taxonomy term counter does not decrease.

- src/Orchard.Web/Modules/Orchard.SecureSocketsLayer/Services/SecureSocketsLayerService.cs
For example, with a hostname = "localhost:44300", the UriBuilder.Host becomes "44300"
> #5113: SecureSocketsLayer, incorrect Hostname when port number is included

- src/Orchard.Web/Core/Common/Models/CommonPart.cs
- src/Orchard.Web/Core/Common/Utilities/LazyField.cs
- src/Orchard.Web/Core/Containers/Models/ContainerPart.cs
- src/Orchard.Web/Core/Navigation/Handlers/MenuPartHandler.cs
- src/Orchard.Web/Modules/Orchard.ArchiveLater/Handlers/ArchiveLaterPartHandler.cs
- src/Orchard.Web/Modules/Orchard.AuditTrail/Models/AuditTrailSettingsPart.cs
- src/Orchard.Web/Modules/Orchard.Azure.MediaServices/Models/Assets/Asset.cs
- src/Orchard.Web/Modules/Orchard.Azure.MediaServices/Models/Jobs/Job.cs
- src/Orchard.Web/Modules/Orchard.Azure.MediaServices/Models/Jobs/Task.cs
- src/Orchard.Web/Modules/Orchard.Comments/Handlers/CommentPartHandler.cs
- src/Orchard.Web/Modules/Orchard.Comments/Handlers/CommentsPartHandler.cs
- src/Orchard.Web/Modules/Orchard.ContentPicker/Handlers/ContentMenuItemPartHandler.cs
- src/Orchard.Web/Modules/Orchard.ContentPicker/Handlers/ContentPickerFieldHandler.cs
- src/Orchard.Web/Modules/Orchard.Email/Handlers/SmtpSettingsPartHandler.cs
- src/Orchard.Web/Modules/Orchard.Localization/Handlers/LocalizationPartHandler.cs
- src/Orchard.Web/Modules/Orchard.MediaLibrary/Handlers/MediaPartHandler.cs
- src/Orchard.Web/Modules/Orchard.MediaPicker/Handlers/MediaGalleryFieldHandler.cs
- src/Orchard.Web/Modules/Orchard.PublishLater/Handlers/PublishLaterPartHandler.cs
- src/Orchard.Web/Modules/Orchard.Roles/Handlers/UserRolesPartHandler.cs
- src/Orchard.Web/Modules/Orchard.Tags/Handlers/TagCloudHandler.cs
- src/Orchard.Web/Modules/Orchard.Taxonomies/Handlers/TaxonomyPartHandler.cs
- src/Orchard.Web/Modules/Orchard.Taxonomies/Handlers/TermsPartHandler.cs
- src/Orchard/ContentManagement/Handlers/StorageFilter.cs
- src/Orchard/ContentManagement/Handlers/StorageVersionFilter.cs
- src/Orchard/ContentManagement/Utilities/LazyField.cs
It closes #765 and closes #3746 and closes #5191.
I removed _value parameter from loader delegate because it was pointless (_value was always null if noone run setter before loader) and it is used nowhere except storage filters.
Please check if all is well.
W.
> Make Orchard.Core.Common.Utilities.LazyField<T> [Obsolete]

- src/Orchard.Web/Modules/Orchard.OutputCache/Filters/OutputCacheFilter.cs
Honestly I have no idea why this code is needed to get charset back into response headers, but it works ...
>  #5224: Fix for missing charset in response header for cached output

- src/Orchard.Web/Modules/Orchard.Workflows/Controllers/AdminController.cs
- src/Orchard.Web/Modules/Orchard.Workflows/Views/Admin/Edit.cshtml
By clearing WorkflowRecords in the submit.Save controller action, the related workflows and their awaiting activities are cleared
> #5235: Awaiting activities not cleared on saving

- src/Orchard.Web/Modules/Orchard.DynamicForms/Views/Elements/EmailField.Design.cshtml
When `email` type is specified on an input it triggers browser validation on that field which prevents administrator from inserting tokens like `{User.Email}`.
> #5109: Email field shouldn't specify email type in design mode

- src/Orchard.Tests/DataMigration/Utilities/NullInterpreter.cs
- src/Orchard/Data/Migration/Interpreters/DefaultDataMigrationInterpreter.cs
- src/Orchard/Data/Migration/Interpreters/IDataMigrationInterpreter.cs
- src/Orchard/Data/Migration/Schema/SchemaBuilder.cs
Sometimes when performing a migration there is work to be done on the database tables.
This PR adds explicit calculation of table name with proper Orchard prefix.
> Provide full table name prefix for migrations

- src/Orchard.Tests.Modules/Recipes/Services/RecipeManagerTests.cs
- src/Orchard.Web/Modules/Orchard.Modules/Controllers/AdminController.cs
- src/Orchard.Web/Modules/Orchard.Recipes/Services/RecipeHarvester.cs
- src/Orchard.Web/Modules/Orchard.Recipes/Services/RecipeParser.cs
Currently, the recipe parser throws any recipe errors to the user, causing full page error on the tenant setup screen or ‘Recipes’ tab in the admin area. It would be beneficial for these errors to be trapped and logged, so that users can still work with valid recipes.
If the RecipeParser validated the recipe text, it could return a null for any invalid files. Any null recipes returned by RecipeParser could then be logged, along with the file name. No error would occur for the user.
The manner in which the user is informed is flexible. I would propose a message on-screen informing them of the problem file or files, as a logging-only solution could mask problems.
There are no breaking changes involved in the implementation of the proposed amendments.
While implementing the change, I noticed …
> Added logging for invalid recipe files

- src/Orchard.Web/Modules/Orchard.OutputCache/Filters/OutputCacheFilter.cs
This will increase performance by a very slight amount (~1ms) on an OOTB install of Orchard. If someone has overridden the virtual `ComputeCacheKey` with more complex logic then the performance gains will be noticeable.
See #5390
> Defers output cache key creation until we know we need it

- src/Orchard.Web/Modules/Orchard.Azure.MediaServices/Web.config
Retargeting to 1.9.x - updated assembly binding from 3.1.0 to 4.3.0
> Assembly binding to azure storage 4.3.0

- src/Orchard.Web/Modules/Orchard.Projections/Services/ProjectionManager.cs
Projections don't order queries following the Position field of each order in the query
Related issue https://github.com/OrchardCMS/Orchard/issues/5426
> Issue #5426 Projections don't order queries following Position field

- src/Orchard.Web/Modules/Orchard.Users/Services/MembershipService.cs
`Orchard.Email.Services.SmtpMessageChannel.Process` expects a string for Recipients, not a string array. This results in an *Object reference not set to an instance of an object* exception and the moderator(s) do not get notified. Fixes #4928.
> Fix moderator notification

- src/Orchard.Web/Modules/Orchard.Setup/Views/Setup/Index.cshtml
The parameter "ENCODING" has been obsoleted by newest Npgsql driver.
Reference:
https://github.com/npgsql/npgsql/wiki/User-Manual
> Fixed the sample of PostgreSQL's connection string

- src/Orchard.Web/Modules/Orchard.AuditTrail/Views/DefinitionTemplates/AuditTrailPartSettings.cshtml
- src/Orchard.Web/Modules/Orchard.MediaProcessing/Services/ImageProfileManager.cs
Image cache is empty after every reboot of the Orchard app. It makes Dynamic ImageProfiles reprocess images after every reboot. It has a big impact on performance because all the images that use dynamic profiles are reprocessed when they are requested after a reboot. When you open a page with a number of images disk usage increases drammatically and the app answer very slow to other requests.
Related with issue https://github.com/OrchardCMS/Orchard/issues/5061
> Issue #5061 GetImageProfileUrl reprocess images obtained through a dynamic profile on every restart

- src/Orchard.Tests/ContentManagement/DefaultContentManagerTests.cs
- src/Orchard/ContentManagement/DefaultContentManager.cs
The new version should always be contentItemRecord.Versions.Max(x => x.Number) + 1; not latestVersion.Number + 1;
I have a scenario where user can delete the draft content. In this scenario, I set the published version to have Latest=true and the draft version to have Latest=false. Now if I have to create again a new draft(by using ContentManager.Get(id, VersionOptions.DraftRequired);) out of the published content, I end up having two versions of the same content items with the same version number.
> Fix for duplicate version number on creating a new draft

- src/Orchard.Web/Modules/Orchard.MediaLibrary/Scripts/media-library.js
Item shape is square in the media library. If item height in orchard-medialibrary-admin.css modified and smaller than item width, the count of items will be wrong. This work fixed the issue.
> Fixed the items count in media library when modify the item size in css

- src/Orchard.Web/Config/HostComponents.config
Added Orchard.Environment.Descriptor.ShellDescriptorCache setting back to HostComponents.config. For some reason, this was removed at some point but I believe it needs to be there for Azure Web Apps deployments (when running with a shared file system and multiple instances).  We were getting instances that would crash when trying to access the locked cache.dat file.
Original commit by @sebastienros
https://github.com/OrchardCMS/Orchard/commit/a2d91796d14b9aa0b7fb1ae97037c9d843680acd
Commit that removed this setting:
https://github.com/OrchardCMS/Orchard/commit/e5d89ea1fbd4bedf574c85ff8d7a8c21513b5d5e
> Fixes #5398 - ShellDescriptorCache in HostComponents

- src/Orchard.Web/Core/Navigation/Views/Admin/Index.cshtml
- src/Orchard.Web/Modules/Orchard.Taxonomies/Views/EditorTemplates/Fields/TaxonomyField.Autocomplete.cshtml
- src/Orchard.Web/Modules/Orchard.Taxonomies/Views/EditorTemplates/Fields/TaxonomyField.cshtml
The CamelFriendly function is designed for Technical Name. The
DisplayName needs to be displayed as it is.
> Delete the CamelFriendly function call to DisplayName.

- src/Orchard/DisplayManagement/Descriptors/ShapePlacementStrategy/ShapePlacementParsingStrategy.cs
In placement files shapeType uses "__" intead of '-' char for declaring a differenciator. The point is second one is used only in template files as can be seen in documentation http://docs.orchardproject.net/Documentation/Accessing-and-rendering-shapes#NamingShapesandTemplates
However GetShapeType looks for '-' character ignoring placements for a ShapeType with a differentiator. This produces strange behaviors and a lot of headaches to users because when they set for example: ```<Place Fields_Common_Text__SeoTitle="/Header:0"/>```  in a placement file it forces all Fields_Common_Text shapes within the same Match to be rendered at Header:0 area instead of only affecting those with the SeoTitle differentiator.
Related to this issue https://github.com/OrchardCMS/Orchard/issues/5432
> Issue #5432 Differentiator is ignored processing placement

- src/Orchard.Web/Modules/Orchard.Projections/Views/Admin/Index.cshtml
Queries Index Page missing Title
> Queries Index Page missing Title

- src/Orchard.Web/Modules/Orchard.DynamicForms/ValidationRules/StringLength.cs
> #5512: Incorrect message of DynamicForms StringLength rule if only Maximum is specified

- src/Orchard.Web/Web.config
I'm not sure that this is something that we want to include globally, but I have had some issues with the following mime maps on Azure.
Specifically, SVG files getting returned as binary, breaking embeds in media library, editors and UI (front and admin).
This may also be directly related to storing media files in azure blob storage (and setting the mimetype when uploading files to blob storage)
> Added mimetype declarations to root web.config

- src/Orchard.Web/Web.config
The new WOFF 2.0 Web Font compression format offers a 30% average gain over WOFF 1.0 (up to 50%+ in some cases).
Can be safely used side-by-side with WOFF 1.0 as only browsers that support it request it. That is according to [Can I Use](http://caniuse.com/#search=woff2) more than 50% global browser usage.
> Added woff2 mimetype

- src/Orchard/Environment/Configuration/AppConfigurationAccessor.cs
Issue #5520.
`AppConfigurationAccessor` will check for a tenant specific key before falling back to the default key. This functionality is similar to that of `PlatformConfigurationAccessor`
> AppConfigurationAccessor is now tenant aware

- src/Gulpfile.js
- src/Package.json
Added support for separation of watch vs build .less files.
This required adding a flag for forcing rebuild, because the watch files may have changed, but the build files may not have, causing rebuild to fail.  Setting the rebuildAlways flag to true forces the rebuild to occur, regardless of files changed.  
Also added an option to exclude sourcemaps.  This defaults to false (include them if not set).
All options are ... wait for it ... optional.
Example Assets.json:
```
[
{
"inputs": [ "Less/master.less" ],
"output": "Styles/@.css",
"watch": ["Less/**/*.less", "Less/*.less"],
"rebuildAlways": true,
"excludeSourceMaps": true
}
]
```
> Fixes #5607 - Assets.json options

- Orchard.proj
We use the orchard packaging script for continuous deployments to QA servers where we'd like to run debug builds.  Previously, the orchard build script supported only packaging a release build.
> Allow for packaging a debug build

- src/Orchard.Web/Modules/Orchard.Search/Controllers/ContentPickerController.cs
- src/Orchard.Web/Modules/Orchard.Search/Controllers/MediaController.cs
- src/Orchard.Web/Modules/Orchard.Search/Routes.cs
Here, fixes only the route issue of #5552. I do it here because it was introduced only in the dev branch, not in the 1.9.x, this after this commit that intoduces a new searchIndex optional parameter in Route.cs
https://github.com/OrchardCMS/Orchard/commit/b88d08b0ff33bc15c840c4307ea5c25f33c44bd7#diff-79bfb04dea87efbf537bf6cfc46d01cd
With the "Search/ContentPicker..." url, ContentPicker was considered as a index name...
Not the case with this more specialized url that also specify the controller action name
"Search/Media/MediaItems..."
I will do another PR on the 1.9.x branch for this 2 last points. Tell me if I have to do it also in the dev branch.
- UPDATE: Finally, I've done all the changes here because the search index and fields implementation has been improved in the dev branch. E.g …
> #5552: ContentPicker Search Route issue

- src/Orchard.Web/Core/Contents/Views/Admin/Create.cshtml
- src/Orchard.Web/Core/Contents/Views/Admin/List.cshtml
- src/Orchard.Web/Modules/Orchard.ContentTypes/Views/Admin/Edit.cshtml
- src/Orchard.Web/Modules/Orchard.ContentTypes/Views/Admin/EditField.cshtml
- src/Orchard.Web/Modules/Orchard.ContentTypes/Views/DisplayTemplates/EditTypeViewModel.cshtml
It's the only workaround if we choose keeping Localizer to default encode arguments.
> Fixes 5591 : ContentType's name encoding

- src/Orchard.Tests/ContentManagement/DynamicContentItemTests.cs
- src/Orchard/ContentManagement/ContentItem.cs
- src/Orchard/ContentManagement/ContentPart.cs
Fixes #5369
Not sure we can do this, but with this changes, with a dynamic ContentItem / ContentPart (e.g got from the Model in a razor view, and not casted to the ContentItem / ContentPart types) I can use the following without throwing an exception
if (contentItem.SomePart != null)
if (part.SomeField != null)
Best
> #5369: Allows simple properties null checking on a dynamic ContentItem or ContentPart

- src/Orchard.Web/Modules/Orchard.MediaLibrary/Views/Fields/MediaLibraryPicker.Summary.cshtml
- src/Orchard.Web/Modules/Orchard.MediaLibrary/Views/Fields/MediaLibraryPicker.SummaryAdmin.cshtml
- src/Orchard.Web/Modules/Orchard.MediaLibrary/Views/Fields/MediaLibraryPicker.cshtml
Field CSS class name should use the technical name, rather than the display name.
> Correct CSS class name of MediaLibraryPickerField field

- src/Orchard.Web/Themes/TheThemeMachine/Styles/Site.css
Set a background color to #layout-footer in Site.css, you can clearly see the blank line at the bottom.
> Remove the blank line at the bottom of every page after the default theme rendering.

- src/Orchard.Web/Modules/Orchard.Taxonomies/Drivers/TaxonomyFieldDriver.cs
Call taxonomyservice to load all the terms for a content item to avoid calling TaxonomyField's Terms property.
> [Fix #5618] taxonomy in autoroute needs to be saved twice

- src/Orchard/Orchard.Framework.csproj
Daniel changed the Orchaard.Framework project to ignore the JetBrains.Annotations conflicts for debug builds several months back. See http://orchard.codeplex.com/workitem/21056 and 78901ba . However, the problem still exists for release builds. This pull request applies the same fix (ignoring the warning) to release builds.
> Suppressed warning CS0436 in Orchard.Framework

- src/Package.json
'npm install' was generating several warnings about missing properties in package.json. Marking the repository as private clears up the warnings.
> Mark the npm repository as private

- src/Orchard/Environment/DefaultOrchardShell.cs
This is a fix for #4852
This fixes some of the problems we are seeing relating to being unable to inject HttpContextBase during IOrchardShellEvents.
This has mainly been a problem when attempting to access ContentManager or site settings in Data Migrations, such as seen in #5305 #5490 #5528.
We seem to only be hitting the problem when Orchard is compiled under VS2015, but this is probably the correct behavior even when building under previous environments.
> #4852: Wrap IOrchardShellEvents in a work context

- src/Orchard.Web/Modules/Orchard.DynamicForms/Drivers/QueryElementDriver.cs
- src/Orchard.Web/Modules/Orchard.DynamicForms/Drivers/TaxonomyElementDriver.cs
This change ensures that value attribute is included in the default (no value selected) option for dropdown select lists that are generated for Query and Taxonomy elements. Fixes #5779
> #5779: Query and Taxonomy Elements should include value attribute for default option

- src/Orchard.Web/Modules/Orchard.Layouts/Models/ElementSessionState.cs
Make Model Serializable for use in Web Farms with session state stored in a database. Currently a Serialization error is thrown when creating layout or page in the dashboard.
> Serialization error is thrown when creating layout or page in the dashboard when using Layouts in a Web Farm.

- src/Orchard.Web/Modules/Orchard.OutputCache/Services/DefaultCacheStorageProvider.cs
- src/Orchard/Environment/WorkContextAccessor.cs
Fixes #5879
And maybe other issues, when the `GetContext(httpContext) method`, the one that has an `HttpContextBase parameter`, is called in the context of a `BackgroundTask`.
> Fixes #5879: Layout part OnIndexing fails when called in a background task

- src/Orchard.Web/Modules/Orchard.CustomForms/Views/Parts.CustomForm.Wrapper.cshtml
Implemented fix for custom form module to eliminate HTML validation error. See original work item here https://orchard.codeplex.com/workitem/20514
Fixes #4343
> Issue 20514 - Remove id from custom form returnUrl hidden field

- src/Orchard/Mvc/MvcModule.cs
The issue is that `CookieCultureSelector` from module Orchard.CulturePicker would face `NotImplementedException` when accessing property `AnonymousID` on a given `HttpRequestBase` object.
The issue is caused by `CookieCultureSelector` is expecting a working implementation of `HttpRequestBase.AnonymousID`, yet in one case that wont'be true. During background task execution, which is started by `SweepGenerator` on a background thread without real HTTP request, the `HttpRequestBase` object is created using `HttpRequestPlaceholder`, which is trying to simulate a valid HTTP Request to some extent, particularly leaving its property `AnonymousID` not implemented. However, `CookieCultureSelector.EvaluateResult` is expecting `context.Request.AnonymousID` being implemented in some way.
This could …
> HttpRequestPlaceholder should implement property AnonymousID

- src/Orchard/Logging/OrchardLog4netLogger.cs
Fixes #5883
By removing, when logging, the ThreadContext Properties for infos that are not available.
> Fixes #5883: Logging thread infos overlapping

- src/Orchard/Commands/Builtin/HelpCommand.cs
closes #422
This makes the orchard.exe `help` command more intuitive. 
Currently it makes you type out the full command to get help on it:
From the way command line's work I think most users would expect `user` to be the command and the rest of the elements are arguments.
This small change filters the help so it just lists all the help it can based on the input:
`> help user`
I decided not to change the help command description:
[CommandHelp("help <command>\r\n\t" + "Display help text for <command>")]
This is because:
- Like I said, users won't realise that orchard considers the actual command to be several words long
- The new filtered help just acts like autocomplete
Reminder note: If help text is deemed to need changing we also need to update text in …
> make orchard help command more intuitive - closes #422

- src/Orchard.Azure/Orchard.Azure.Web/Orchard.Azure.Web.csproj
This fixes a problem when using cloud services. The Azure web project had lost the msbuild tasks that copy the core, modules and themes folders from the Orchard.Web project over to the Azure Web project
> Fix for orchard issue #5869

- src/Orchard.Web/Modules/Orchard.ContentPicker/Orchard.ContentPicker.csproj
- src/Orchard.Web/Modules/Orchard.ContentPicker/ResourceManifest.cs
- src/Orchard.Web/Modules/Orchard.ContentPicker/Scripts/ContentPicker.js
- src/Orchard.Web/Modules/Orchard.ContentPicker/Scripts/RecentContentTab.js
- src/Orchard.Web/Modules/Orchard.ContentPicker/Scripts/SelectableContentTab.js
- src/Orchard.Web/Modules/Orchard.ContentPicker/Styles/ContentPicker.css
- src/Orchard.Web/Modules/Orchard.ContentPicker/Views/ContentPicker.SummaryAdmin.cshtml
- src/Orchard.Web/Modules/Orchard.ContentPicker/Views/RecentContentTab.cshtml
- src/Orchard.Web/Modules/Orchard.Search/Views/SearchContentTab.cshtml
We needed the ability to create a custom tab on the contentPicker for the new layouts to allow our clients the ability to paste a list of ID's into.  In doing so, I found I needed to modify the contentPicker.js callback to handle an array of items.  I would love for contentPicker.js to be submitted on it's own but felt that a more complete solution would be more beneficial.  With this addition I have added new checkbox's for each content item in addition to the select button.  I added a new button at the bottom of the list to add the checked content items.  Once the add items button is click the window closes as does the current behavior for select buttons.  If the user experience of this new behavior does not pass review, I ask that you consider keeping the contentPicker.js changes as …
> Enhancement to allow multi-select for the content picker

- src/Orchard.Web/Modules/Orchard.Autoroute/Drivers/AutoroutePartDriver.cs
This should fix issue #5885, the DisplayAlias not having length validated. I arbitrarily set it to 1850 for the simple fact that, while the database can hold a 2048 character DisplayAlias, a URL should not be longer than ~2000 characters (per http://stackoverflow.com/questions/417142/what-is-the-maximum-length-of-a-url-in-different-browsers ). If the DisplayAlias is 2048, it's already over the limit and that's not the entire URL for the page, this gives some buffer room for domains.
> Fixes #5885

- src/Orchard.Web/Modules/Orchard.Layouts/Scripts/dialog.js
When an Element is being edited, it is done in an iframe embedded in a dialog box that appears over the Layout editor. The "Save" button is handled outside the iframe, and when it is clicked, jQuery code looks for the form inside the iframe and submits it.
The problem is that since the outer window's jQuery is used to submit the form that belongs to the iframe, it does not trigger any of the event handlers that may have been placed on the form by code inside the iframe.
For example, often I need to perform serialization of data (such as serializing a knockoutjs view model to a hidden field) or validation inside an editor. The code in the form would set an event handler on the submit event of the form. Validation could prevent the submission of the form if there are problems.
My fix uses …
> With the Element editor dialog, use dialog iframe's jQuery for form submission

- src/Orchard.Web/Modules/Orchard.DynamicForms/Drivers/UrlFieldElementDriver.cs
- src/Orchard.Web/Modules/Orchard.DynamicForms/Elements/UrlField.cs
- src/Orchard.Web/Modules/Orchard.DynamicForms/Orchard.DynamicForms.csproj
- src/Orchard.Web/Modules/Orchard.DynamicForms/ValidationRules/UrlAddress.cs
- src/Orchard.Web/Modules/Orchard.DynamicForms/Validators/Settings/UrlFieldValidationSettings.cs
- src/Orchard.Web/Modules/Orchard.DynamicForms/Validators/UrlFieldValidator.cs
- src/Orchard.Web/Modules/Orchard.DynamicForms/Views/Elements/UrlField.Design.cshtml
- src/Orchard.Web/Modules/Orchard.DynamicForms/Views/Elements/UrlField.cshtml
Created this because I was binding to a content type that had a URL field. Needed to do this validation when submitting the dynamic form.
> Resolves #5878 : URL Field for Dynamic Forms

- src/Orchard.Web/Modules/Orchard.JobsQueue/Services/JobsQueueProcessor.cs
Fixes #5882
Where I get this warning every minute just by enabling the job queue feature.
The problem is when it's always the same instance of `IDistributedLockService` (even there is one per shell) that is executed as in `JobsQueueProcessor` because it's an `ISingletonDependency`.
Best
> #5882: No record could be found in the database for lock

- src/Orchard.Tests/Mvc/Html/HtmlHelperExtensionsTests.cs
- src/Orchard.Tests/Utility/Extensions/StringExtensionsTests.cs
- src/Orchard/Mvc/Html/HtmlHelperExtensions.cs
- src/Orchard/Utility/Extensions/StringExtensions.cs
I fixed `Excerpt` and `Ellipsize` `HtmlHelperExtensions`'s methods.
I also updated  `Ellipsize` `StringExtensions`'s method as we can't assume it deals with HTML encoded strings, and the related test.
> Fixes #6023 : Ellipsize can spilt an HTML encoded character

- src/Orchard.Web/Core/Contents/AdminMenu.cs
- src/Orchard/ContentManagement/DefaultContentQuery.cs
Suggested solution to [Issue 6043](https://github.com/OrchardCMS/Orchard/issues/6043)
Previously, when no content type names where provided (from a prior conditional statement, so there is an initialized array but it is empty) then the filtering steps are skipped and instead of serving "no content
types", as an empty array would state: all content types are served.
When contentTypeNamed.Length == 0, still .Select() as this is safe for empty collections and will filter out all types in this event.
Any feedback or sidcussion welcome.
> Filter out when no contentTypeNames provided

- src/Orchard.Web/Modules/Orchard.Comments/Views/Parts.Comment.cshtml
1. Fixed comment links so that when the user clicks on comment metadata on the front end the desired scrolling effect is achieved.
2. Added a `.has-replies` class to comments that have replies for easier styling.
3. Stopped the comment reply button from showing when comments are disabled. Also needs fixing to not display the reply button if a user doesn't have permission to post comments.
4. Removed span around reply button as it adds no ease to styling.
> Fixed reply button and comment link and added useful CSS class.

- src/Orchard.Web/Modules/Orchard.MediaLibrary/Scripts/media-library-picker.js
- src/Orchard.Web/Modules/Orchard.MediaLibrary/Styles/dialog-mode.css
fixes #5978 by moving the select button to the top of the media picker window **when in modal window  only** and hides the save button untill some image is selected
> fixes #5978

- src/Orchard.Web/Modules/Orchard.Tokens/Implementation/Tokenizer.cs
This brings Tokenizer changes from changeset
423fec90b3494a2482ec186ad521862e9ed7be1e.
> Fix handling braces in tokens

- src/Orchard.Web/Core/Settings/State/ShellStateManager.cs
- src/Orchard/Environment/Features/FeatureManager.cs
Avoids many retrievals of ShellStateRecord and stops enabling the same
feature multiple times. This can significantly improve recipe execution
time for those recipes with large numbers of features with long
dependency chains.
> Added two optimisations to avoid duplicate work

- src/Orchard/ContentManagement/MetaData/Builders/ContentPartDefinitionBuilder.cs
SingleOrDefault will throw an error when removing fields with the same name.  Should be FirstOrDefault as it is on line 64
> Removing duplicate fields from content parts fails

- src/Orchard.Web/Modules/Orchard.Widgets/Services/DefaultLayerEvaluationService.cs
Sorry for trying to revert this PR related to the awesome presentation of Chris Payne at Harvest where a `QueryHints()` with `ExpandParts()` was added to access the layer parts...
But after the query, as mentioned in a meeting by Sébastien, a previous version was used with access to the LayerPartRecord `activeLayer.Record.LayerRule`. But now, because the LayerRule is in the infoset, we only use `activeLayer.LayerRule`.
So, this PR requested by @sebastienros 
Note1: the substance of the Harvest presentation remains fully relevant.
Note2: not tested but validated by Sébastien. If wrong it's not my PR.
Best
> Trying to revert a famous PR, sorry

- src/Orchard.Web/Modules/Orchard.Tokens/Implementation/Tokenizer.cs
Fixes #6193 
For the 2 versions of TokenFilter (for content part / element), context data are not passed in the same way and can be empty. Then, a first running filter can kill the token.
So the need to null check the token replacement value.
Best
> #6193: TokenFilters Cohabitation

- src/Orchard/Localization/LocalizedString.cs
- src/Orchard/Logging/OrchardLog4netLogger.cs
- src/Tools/Orchard/Host/CommandHost.cs
- src/Tools/Orchard/Logger.cs
- src/Tools/Orchard/OrchardParameters.cs
- src/Tools/Orchard/ResponseFiles/ResponseFileReader.cs
Long-running Orchard commands crashed the command line due to expired leases on remote proxies for MarshalByRef parameters passed in cross-AppDomain calls.
> Fixed issue  #1978

- src/Orchard.Web/Modules/Orchard.MediaLibrary/Scripts/media-library-picker.js
Stops `media-library-picker.js` starting media ids list with a comma.
There is no issue with `MediaLibraryPickerField` as it uses `StringSplitOptions.RemoveEmptyEntries`, but it's an issue if you use `MediaLibraryPicker` shape and expect a single id.
The fix slightly reduces DOM access, it should not be bad.
> Fix media-library-picker.js

- src/Orchard.Web/Modules/Orchard.OutputCache/Filters/OutputCacheFilter.cs
- Use `String.Interned` strings to remove reliance on a concurrent dictionary
- Removing timeout to rely on the request timeout itself
- Adding a finalizer to catch any locked resource
@DanielStolt
> Improving monitors usage for output cache

- src/Orchard.Web/Modules/Orchard.ImportExport/Providers/ImportActions/ExecuteRecipeAction.cs
Fixes #6181 
When running Import/Export at the console it would fail due to a null HttpContext.
* Added a guard clause as  HttpContext is not available when running at console
> Fixed bad assumption about HttpContext

- src/Orchard/ContentManagement/XmlHelper.cs
This enables content parts to use infoset storage with nullable enum types.
Before this change, the NotSupportedException would be thrown.
> Added handling of nullable enums.

- src/Orchard/Environment/WorkContextImplementation.cs
Fixes #6192
Already done in the dev branch, but because it fixes an issue if applied to 1.9.x.
Best
> #6192: Uses Lazy IWorkContextStateProvider in 1.9.x, as done in the dev branch.

- src/Orchard.Web/Modules/Orchard.Localization/Views/FrontEndCultureSelector.cshtml
When using this view and the current home page does not have, or has not yet, a localizable part and / or a culture defined.
E.g, a localizable part isn't added automaticaly to a blog container, so when promoting a blog to the "home page"...
Best
> Little update to FrontEndCultureSelector.cshtml

- src/Orchard.Web/Modules/Orchard.MediaProcessing/Services/ImageProfileManager.cs
Treatment null value for params argument. (When null value of nullable type T is passed as params argument that it will be converted to array of type T with one null member).
Without it Display.MediaUrl(Profile: "ProfileName", Path: "image-path.jpg") which call GetImageProfileUrl with null customFilter doesn't work.
> Treatment null value for params argument inside ImageProfileManager

- src/Orchard/Mvc/Extensions/HttpContextBaseExtensions.cs
- src/Orchard/Mvc/HttpContextAccessor.cs
As suggested by @sfmskywalker somewhere in this issue #6321 where he fixed it by using a private method that use the same code as an existing static method. So, he suggested to me to do this extension helper.
We already have the `IsBackgroundContext()` extension to check for a fake `HttpContextBase`. This one is to check for a fake `HttpContext`. Can be useful where `HttpContext.Current` is used directly. Then, for example, we could use this:
if (HttpContext.Current.IsBackgroundHttpContext()) {
Best.
> New IsBackgroundHttpContext() extension helper.

- src/Orchard.Web/Modules/Orchard.DynamicForms/Drivers/FormElementDriver.cs
- src/Orchard.Web/Modules/Orchard.DynamicForms/Elements/Form.cs
If we want to default encode form values, an alternative to this PR would be a checkbox to opt-out HtmlEncoding.
More, HtmlEncoded form values are not correctly diplayed in Form Submissions view.
> Fixes #5593 : Allow disabling HtmlEncode on DynamicForms

- src/Orchard.Web/Modules/Orchard.Alias/AdminMenu.cs
This removes the broken file reference for stylesheet `/Themes/TheAdmin/styles/menu.aliases-admin.css` generated by the Orchard.Alias UI feature.
> [Fixes #6430] Removes Imageset for Orchard.Alias UI

- src/Orchard.Web/Modules/Orchard.MediaLibrary/Styles/orchard-medialibrary-admin.css
Sets the height of the media library container to the height of the content (with padding)
> [Fixes #6454] Sets the height of the media library correctly

- src/Orchard.Web/Modules/Orchard.Packaging/Styles/orchard-packaging-admin.css
Previously when it was on an alt bg colour or mouse hover you could see the background:
This fixes it so that it displays like this:
> fix display glitch in admin packaging/gallery/modules

- src/Orchard.Web/Modules/Orchard.Redis/Caching/RedisCacheStorageProvider.cs
default(T) returns non null value for primitive datatypes, this causes `CachingExtensions.Get<T>` never to call the factory method.
> Incorrect data being returned for nonexistent primitive datatypes

- src/Orchard.Web/Modules/Orchard.DynamicForms/Drivers/BindingsElementDriver.cs
fixes #5706 - standardize order on Properties, Validation, Bindings
previously validation and bindings tabs sometimes switched places
I checked every ootb form element and they all show the correct order with this change
> fixes #5706 - standardize order on Properties, Validation, Bindings

- src/Orchard.Web/Modules/Orchard.Modules/styles/orchard-modules-admin.css
Fixes #5907 convert modules admin page to use css flexbox
Summary view now stretches when needed on a per row basis and keeps alignment:
Previously "Depends on" would be cut off for long lists like Blogs.
Detail view is converted to column flexbox as well:
I artificially inflated the Blog dependencies to confirm that it expands correctly.
> Fixes #5907 convert modules admin page to use css flexbox

- src/Orchard.Web/Core/Common/Drivers/TextFieldDriver.cs
- src/Orchard.Web/Modules/Orchard.Fields/Drivers/TextFieldDriver.cs
Replaces #6535 to target 1.10.
**Issues**
1. **When you 1st create** e.g a page that has a text field that has a default value. If you input a non empty string and publish, then the default value is used (not your input). The 2nd time it's ok.
2. Idem but leaving the input empty, then the default value is used, ok, but if it's a token, the token itself is returned, it is not resolved. The 2nd time it's ok.
3. If i only fix 1. (see below), then the default value is never tokenized.
Note: To allow default values tokenization, a 2nd `TextField` driver has been added  in `Orchard.Fields`.
**Fixes**
1. In the original driver i've re-integrated `field.Value = viewModel.Text;`.
2. In the 2nd driver, if the default is not null and the value is equals to the default, then the default is tokenized. …
> Replaces #6535 to target 1.10: Issue with TextField default values

- src/Orchard.Specs/MultiTenancy.feature
- src/Orchard.Specs/MultiTenancy.feature.cs
Since 1b8bcb8 where a host OR prefix is required when creating a tenant.
Notice that i've tested it on the dev branch but by applying the above commit. Then, indeed `ANewTenantIsCreated` and `ANewTenantIsCreatedWithUninitializedState` was failing.
After applying this fix, the 2 above specs passed.
Here, i've manually changed the Feature file and it's related Feature.cs file. Would i have had to use a tool to generate this file?
Best
> Fix 2 multitenant specflows issues on nightly build 1.9.x

- src/Orchard.Web/Modules/Orchard.OutputCache/Filters/OutputCacheFilter.cs
- src/Orchard.Web/Modules/Orchard.OutputCache/Models/CacheItem.cs
- src/Orchard.Web/Modules/Orchard.OutputCache/Services/DefaultCacheStorageProvider.cs
When an HTTP client contains a page locally and requests the same url again, it sends and `ETag` which is an identifier for the content of the page, with the request. If the server knows that the content hasn't changed, it can answer with `304` and no content. The goal is that there is not useless traffic between the server and the client.
Testing the feature:
- Send a request to any url
- Ensure the response contains a specific `ETag` header
- Send the same request, its headers should have a `If-None-Match: [ETAGVALUE]`
- The result should be coming from the cache, as a 304, with the same `ETag` header, and no body
- Send a `no-cache` request (CTRL+F5), the result should have a different `ETag`, and the full body
/cc @DanielStolt @Piedone for review
> Adding correct ETag support

- src/Orchard.Web/Modules/Orchard.Resources/Orchard.Resources.csproj
- src/Orchard.Web/Modules/Orchard.Resources/jQuery.cs
jQuery-UI wasn't included in the solution, which prevents it from being copied to the output directory when building.
There was a typo in the resource declaration of the jQueryTimeEntry script which prevented the minified version from loading.
> [1.10.x] Include jQuery-UI in the Orchard.Resources csproj and fix jQueryTimeEntry script loading

- src/Orchard/DisplayManagement/Implementation/DefaultDisplayManager.cs
Replace #6478 to target 1.10.x
Because we provide a fake context in the background, sometimes we have to replace `HttpContext != null` with `!HttpContext.IsBackgroundContext()` when it doesn't make sense to do anything. Here we have to do the opposite to retrieve the `CurrentTheme` needed to find the snippet razor view.
More details here #6478.
Best.
> [1.10.x] Fixes Layout OnIndexing when using a snippet element

- src/Orchard.Web/Modules/Orchard.ContentPicker/Views/EditorTemplates/Parts.ContentMenuItem.Edit.cshtml
Fixes in one place #6542 
When using the new `Add Selected` button that allow to select multiple items in the content picker view, the returned data is not an item but an array of items. Some scripts that consume these data has been updated but not in all places.
Here, because a content menu item only needs one related item, if data is an array we only use the first one.
Best
> #6542: [1.10.x] Little issue with content picker

- src/Orchard.Web/Modules/Orchard.Layouts/Framework/Drivers/FormsElementDriver.cs
Fixes #6302, fixes #6527. Here, a summary of related PRs and issues.
In a form element editor, if a checkbox is saved as checked, you can't save it again as unchecked. This comes from the fact that if unchecked no value is posted. I also had the same kind of issue with the CreateUser activity in worflows, but here only if i define (in the code) the checkbox as initially checked.
As proposed by @jersiovic here #6527 we could add an hidden input, as done by mvc helper. This works when you bind to a strongly typed model that has a bool property. Then, the value provider convert `true,false` to `true`. But layouts and worflows use different ways with dynamic data.
Indeed, we also needed to change a little how element data are updated. But we would also need to do the same for activities, and …
> #6302: [1.10.x] checkboxes issues in form elements editors

- src/Orchard.Specs/Boolean.feature
- src/Orchard.Specs/Boolean.feature.cs
- src/Orchard.Specs/Enumeration.feature
- src/Orchard.Specs/Enumeration.feature.cs
- src/Orchard.Web/Modules/Orchard.Fields/Drivers/BooleanFieldDriver.cs
- src/Orchard.Web/Modules/Orchard.Fields/Drivers/EnumerationFieldDriver.cs
- src/Orchard.Web/Modules/Orchard.Fields/Views/EditorTemplates/Fields/Enumeration.Edit.cshtml
Fixes #6550. (with other related PRs)
Note: i didn't have a look on other custom fields as TaxonomyField... Only those in Orchard.Fields.
**EnumerationField**
Unlike other fields, here the default value was not used in the Editor method that updates the model but in the other one, this on first creation to have a predefined value. Let me know if we need this on other fields, or if it's case by case. Right now, i left it.
- Anyway, i also use the default value in the editor method that update the model, as with other fields. Then, when another submission happens with no selected option, we can re-use the default value (even it has been changed in the settings). And this before the required checking on server side.
- When using the default value, we retain only its valid options (according …
> #6550: [1.10.x] no client required if default set (enum + boolean fields)

- src/Orchard.Specs/DateTime.feature
- src/Orchard.Specs/DateTime.feature.cs
- src/Orchard.Specs/Input.feature
- src/Orchard.Specs/Input.feature.cs
- src/Orchard.Specs/Link.feature
- src/Orchard.Specs/Link.feature.cs
- src/Orchard.Web/Modules/Orchard.Fields/Drivers/DateTimeFieldDriver.cs
- src/Orchard.Web/Modules/Orchard.Fields/Drivers/InputFieldDriver.cs
- src/Orchard.Web/Modules/Orchard.Fields/Drivers/LinkFieldDriver.cs
- src/Orchard.Web/Modules/Orchard.Fields/Views/DefinitionTemplates/InputFieldSettings.cshtml
- src/Orchard.Web/Modules/Orchard.Fields/Views/EditorTemplates/Fields/Input.Edit.cshtml
- src/Orchard.Web/Modules/Orchard.Fields/Views/EditorTemplates/Fields/Link.Edit.cshtml
Fixes partially #6550. (todo: enum + boolean fields)
**DateTimeField** (many options to check here)
- There is no client required attribute because of the DateTimeEditor.
- As before, if required and one field is missing, editor data are not parsed.
- But, now, before adding an error, we try to use the default value.
**Special case:** When both Date and Time are required, we consider that both input fields are required. But we use the default value only if all required fields are empty. If not, there is an error message as before, input fields need to be completed or completely cleared to use the default.
Note: The DateTime.Feature spec pass.
**InputField**
- Here, no need to change the InputFieldDriver.
- Just remove client required attribute (not the class) if a default value is set.
- …
> #6550: [1.10.x] no client required if default set (input + link + date fields)

- src/Orchard.Specs/Numeric.feature
- src/Orchard.Specs/Numeric.feature.cs
- src/Orchard.Web/Modules/Orchard.Fields/Drivers/NumericFieldDriver.cs
- src/Orchard.Web/Modules/Orchard.Fields/Views/EditorTemplates/Fields/Numeric.Edit.cshtml
Fixes partially #6550.
- If required and a default value: no required on client, still with the red star, and still required on server.
- If a default value is used, control and conversion are done by the same code, as for an user input.
- When a default value is a valid number but not validated (limits / scale), it's value is seen on the postback view. This by using in the view a `Value` attribute. Let me know if you think it's ok.
- But, as before, if the default value is not a valid number, there is no direct way to show it on the postback view. So, i've adapted the error message: `{0} or its default value is an invalid number`.
**Note**: The Numeric.Feature spec pass.
Best
> #6550: [1.10.x] no required on client side if default value is set (NumericField)

- src/Orchard.Web/Modules/Orchard.Azure/Services/FileSystems/AzureFileSystem.cs
- src/Orchard.Web/Modules/Orchard.Azure/Services/FileSystems/Media/AzureBlobStorageProvider.cs
Removes port when default in PublicUrl.
`GetStoragePath` recognizes endpoint and public hostnames.
> #6639 : Azure Media Storage don't recognizes its own URLs

- src/Orchard/Environment/DefaultOrchardHost.cs
Not tried other things, just seen that we have to break the retry loop in place of returning.
Best.
> [1.10.x] [Dev] Processing Engine Tasks not evaluated on startup

- src/Orchard.Web/Modules/Orchard.Taxonomies/Migrations.cs
> Fix #6275: Give TaxonomyNavigationMenuItem an Identity

- src/Orchard.Web/Modules/Orchard.OutputCache/Filters/OutputCacheFilter.cs
This wasn't raising awareness in Orchard community as the official code base does not use Child Actions (they use shapes).
Previously there is reentrancy-prevention code in OnResultExecuted to filter out Child Actions so that OnResultExecuted only gets executed once per request and only for the parent Action. However, this reentrancy-prevention code is being incorrectly placed in the try-catch block, that the finally-block can get executed more than once if parent Action includes any Child Action. This wasn't an issue until commit 117dd09f (first included in release 1.10) which resets _cacheKey in that finally-block via ReleaseCacheKeyLock. Now for every request that uses Child Actions, the finally block will be executed at least once during Child Action's OnResultExecuted, leaving the …
> Fix #6721: Fix an issue that ChildAction will incorrectly reset _cacheKey for OutputCacheFilter

- src/Orchard/Tasks/Locking/Services/DistributedLockService.cs
This fixes an issue with creating new distributed lock records while a record with the specified name already exists (but with a different ValidUntilUtc value) by deleting any existing (and expired) records first of the specified name.
> Fixed removal of records in DistributedLockService.

- src/Orchard/Data/Migration/AutomaticDataMigrations.cs
- src/Orchard/Tasks/Locking/Services/DistributedLockSchemaBuilder.cs
When checking if the "Orchard_Framework_DistributedLockRecord" exists, a select on the table is performed. When the table does not exist, this throws an exception.
In PostgreSQL, this sets the transaction in an Error state. Because of this, the transaction accepts no other commands, and the table is never created.
This pull request works around this, by starting a new transaction to create the table  
@OrchardCMS
> Workaround to avoid Transaction issue for PostgreSQL when creating DistributedLocks table

- src/Orchard.Web/Modules/Orchard.Fields/Views/EditorTemplates/Fields/Link.Edit.cshtml
So the `Link.Edit.cshtml` fails.
Just seen that the placeholder settings is defined in the dev branch, not in 1.10.x.
Best.
> [1.10.x] Link placeholder used but doesn't exist in settings

- src/Orchard.Web/Themes/TheAdmin/Scripts/admin.js
Fixes #6788 
@sebastienros 
Just because i still have some drawbacks with your last `multi-submission` checking, here, a proposed solution which seems to work. So, based on the last implementation but:
- Without using `e.preventDefault()` at the end. This to submit the form.
- And without adding to the buttons the disabled property. Otherwise the button value e.g `submit.Publish` is not used and e.g you will not see `Your Page has been saved`.
Note: as before, this only acts on forms with the `no-multisubmit` class.
Best.
> Fixing multi-submission

- src/Orchard.Web/Modules/Lucene/Models/LuceneSearchHit.cs
inside public string GetString(string name) {
var field = _doc.GetField(name);
return field == null ? null : field.StringValue;
}
if field=null, then arg null ex for int.Parse
> avoid potential arg null ex

- src/Orchard.Web/Modules/Orchard.AuditTrail/Orchard.AuditTrail.csproj
- src/Orchard.Web/Modules/Orchard.Azure.MediaServices/Orchard.Azure.MediaServices.csproj
- src/Orchard.Web/Modules/Orchard.Caching/Orchard.Caching.csproj
- src/Orchard.Web/Modules/Orchard.CodeGeneration/CodeGenerationTemplates/ModuleCsProj.txt
- src/Orchard.Web/Modules/Orchard.CodeGeneration/Commands/CodeGenerationCommands.cs
- src/Orchard.Web/Modules/Orchard.Conditions/Orchard.Conditions.csproj
- src/Orchard.Web/Modules/Orchard.Dashboards/Orchard.Dashboards.csproj
- src/Orchard.Web/Modules/Orchard.DynamicForms/Orchard.DynamicForms.csproj
- src/Orchard.Web/Modules/Orchard.Layouts/Orchard.Layouts.csproj
- src/Orchard.Web/Modules/Orchard.MessageBus/Orchard.MessageBus.csproj
- src/Orchard.Web/Modules/Orchard.OutputCache/Orchard.OutputCache.csproj
- src/Orchard.Web/Modules/Orchard.Redis/Orchard.Redis.csproj
- src/Orchard.Web/Modules/Orchard.Resources/Orchard.Resources.csproj
- src/Orchard.Web/Modules/Orchard.Templates/Orchard.Templates.csproj
- src/Orchard.Web/Modules/Upgrade/Upgrade.csproj
Fix for issue #5143 and root cause of several recurring issues related to AssemblyInfo being set to Content instead of Compile.
Updated CodeGen CL to add AssemblyInfo as Compile instead of content, in addition updated existing modules which had AssemblyInfo set to content:
- Orchard.AuditTrail
- Orchard.Azure.MediaServices
- Orchard.Caching
- Orchard.Conditions
- Orchard.Dashboards
- Orchard.DynamicForms
- Orchard.Layouts
- Orchard.MessageBus
- Orchard.OutputCache
- Orchard.Redis
- Orchard.Resources
- Orchard.Templates
- Upgrade
Smoketest passed commands:
codegen module <name>
codegen datamigration <name>
codegen moduletests <name>
codegen theme <name>
codegen theme <name> /createproject:true
Build with unit tests passed.
> #5143 AssemblyInfo build action Compile instead of Content with CodeGen update

- src/Orchard.Web/Modules/Orchard.SecureSocketsLayer/Services/SecureSocketsLayerService.cs
When enabling SSL using module Orchard.SecureSocketsLayer and configuring a specific URL to be secured, e.g. "~/contact", then this URL is not redirected to https as expected.
This is fixed by the one-word update in this PR.
> #5294 Fixed Specific url's in SecureSocketsLayer not redirected to https

- src/Orchard.Web/Modules/Orchard.OutputCache/Filters/OutputCacheFilter.cs
Fixes https://github.com/OrchardCMS/Orchard/issues/6863
By default request header "HOST" is taken into account by GetCacheKeyParameters method.
Problem is it is in upper case "HOST" and in request header the key is "Host".
When requestHeaders.AllKeys.Contains(varyByRequestHeader) is evaluated result is false.
> #6863 Fixed problem with case comparison when checking request headers in output cache

- src/Orchard.Web/Modules/Orchard.MediaProcessing/Services/ImageProfileManager.cs
Uri.IsWellFormedUriString fails with absolute file uri validation. So using Uri.TryCreate to validate the uri.
> Fix for profile image creation failing with absolute uri

- src/Orchard.Web/Modules/Orchard.Layouts/Views/Element/Create.cshtml
- src/Orchard.Web/Modules/Orchard.Layouts/Views/Element/Edit.cshtml
fixes #6877 - wrap text in views with t()
retargeted to 1.10.x from #6878
> fixes #6877 - wrap text in views with t()

- src/Orchard.Web/Modules/Orchard.AuditTrail/Providers/Content/GlobalContentHandler.cs
- src/Orchard.Web/Modules/Orchard.AuditTrail/Services/DiffGramAnalyzer.cs
- src/Orchard.Web/Modules/Orchard.Comments/Controllers/CommentController.cs
Fixes #6733 - **Rebased on dev branch**
@sebastienros here the best compromise i've found to fix the issue without breaking a first original one.
**Summary**
- If audit trail enabled, on a new comment errors are logged and bad event records are created. The audit trail handler rely on a created item and the comment controller creates it after model validation.
- A previous PR #6734 proposed to do a create before update editor (as in other controllers) but, for comments with many items / spams, it's good to preserve transaction logs when model validation fails.
- Another concern is not to conflict with another issue when sending an e-mail on comment publication, the model need to be validated. That's why the create was originally moved after model checking.
**Best compromise i've found**
- …
> #6733: Fix Comments and Audit Trail issue, rebased on dev branch

- src/Orchard.Tests.Modules/Comments/Services/CommentServiceTests.cs
- src/Orchard/Environment/DefaultOrchardHost.cs
- src/Orchard/Environment/DefaultOrchardShell.cs
- src/Orchard/Environment/IOrchardShell.cs
- src/Orchard/Environment/State/DefaultProcessingEngine.cs
- src/Orchard/Environment/State/IProcessingEngine.cs
Fixes #6742 
- On startup, for each tenant, explicitly init the PE tasks list in a new (isolated from its parent) logical context, this at the beginning of the desired parent thread.
- On startup, for each tenant, suspend the background timer until the PE tasks list is fully evaluated.
On startup, a shell and its bg timer are activated in the same logical context, so the PE list is shared with bg tasks. So, maybe good to also init (isolate) the PE tasks list at the beginning of the background service. But here it's not needed because bg tasks are suspended while evaluating the PE list.
Best.
> PE tasks list init and start background timer after PE tasks.

- src/Orchard/UI/Navigation/NavigationHelper.cs
Marking menu item as active is not always right.
It's wrong for situation when first element of second menu level and element of first menu level links to same url:
* homepage (~/)
* about us (~/about-us)
* about as (~/about-us)
* our news (~/about-us/our-news)
* news 1 (~/about-us/our-news/news-1)
* news 2 (~/about-us/our-news/news-2)
* contacts
News 1 and News 2 are not actually added to menu but have respective url.
When current (routed) page is "news 1" then "about as" page from second menu level is marked active (instead of "our news" page)
This pull request solves that problem.
> When selected path is being looked for menu by comparing string-based url It should select most nested url

- src/Orchard.Web/Modules/Orchard.Users/Services/MembershipService.cs
When you run more than one Orchard CMS site, and you have to moderate the logins, it's nice to know which site a new account was created on.
> Add SiteName to New Account Subject

- src/Orchard.Web/Modules/Orchard.OutputCache/Filters/OutputCacheFilter.cs
Fixed the output caching of non 200 responses when exceptions are thrown by views, htmlhelpers, etc.
> Fixed the output caching of non 200  - fixes #7034

- src/Orchard/Data/Migration/AutomaticDataMigrations.cs
Fixes #6783 
This PR #6729 solved an issue with `PostgreSQL` but introduced a little drawback e.g with `SqlCe`, see in #6783. As said by @sebastienros we would need to revert #6729 ...
Here, i propose the same workaround for `PostgreSQL` without breaking other providers, e.g `SqlServer`.
Best.
> #6783: Workaround for PostgreSQL without breaking SQL server.

- src/Orchard.Web/Modules/Orchard.Users/Activities/CreateUserActivity.cs
if the user creates a user name with whitespaces at the end or the start this will cause you a lot of problems with physical paths and the virtual ones,because in physicals you can't have whitespaces but in the orchard objects you'll have the paths with the whitespaces (using the user name with the whitespaces to compose the path)
> User name format in CreateUserActivity

- src/Orchard.Web/Modules/Orchard.Widgets/Layouts/Providers/WidgetElementHarvester.cs
**In this PR**
- While helping someone which uses a projection element with a custom display type to render each content, we needed to pass the right diplay type to widget elements.
**Another suggestion**
- When in `Design` mode, because the actual `Projection.Design.cshtml` only uses the `ContentItems` collection, to prevent many handler / driver from being executed, we could use this in `ProjectionElementDriver.OnDisplaying()`.
```
// after this line
context.ElementShape.ContentItems = contentItems;
// Nothing more to do if we are in "Design" mode.
if (context.DisplayType == "Design") {
return;
}
```
But i didn't include this in this PR because maybe we still want to be able to override `Projection.Design.cshtml` if someone want to render more things in design mode ... So let me know. …
> Pass the right display type to the widget element.

- src/Orchard.Web/Modules/Orchard.Layouts/Helpers/TagBuilderExtensions.cs
Add shape attributes to "TagBuilderExtensions.CreateElementTagBuilder()", to give developers the ability to add there new attribute from custom layout elements drivers.
> Fix #6812: Add shape attributes to "CreateElementTagBuilder"

- src/Orchard.Web/Modules/Orchard.Widgets/Views/EditorTemplates/Parts.Widgets.LayerPart.cshtml
Fixes #7121
Correct url is now:
http://docs.orchardproject.net/en/latest/Documentation/Managing-widgets/#adding-a-layer
> Fixes #7121 Fix incorrect url to docs for layer rules

- src/Orchard.Web/Modules/Orchard.Fields/Views/DefinitionTemplates/BooleanFieldSettings.cshtml
- src/Orchard.Web/Modules/Orchard.Fields/Views/DefinitionTemplates/EnumerationFieldSettings.cshtml
- src/Orchard.Web/Modules/Orchard.Fields/Views/DefinitionTemplates/InputFieldSettings.cshtml
- src/Orchard.Web/Modules/Orchard.Fields/Views/DefinitionTemplates/LinkFieldSettings.cshtml
- src/Orchard.Web/Modules/Orchard.Fields/Views/DefinitionTemplates/NumericFieldSettings.cshtml
fixes #7144 
It was a copy / paste issue thats been lurking around for years. `.forpicker` only exists in the datetimeeditor css file but many fields editors had obviously been copied from that initial snippet because they had the class.
> [fixes #7144] labels hidden when datetime field added

- src/Orchard.Web/Modules/Orchard.Blogs/Views/Content-Blog.Edit.cshtml
Fixes #7142 
Starts off with either `\Views\BlogAdmin\Create.cshtml` or `\Views\BlogAdmin\Edit.cshtml` which set correct heading. 
Both controller actions use `\Views\Content-Blog.Edit.cshtml` which set the title a second time.
> [Fixes #7142] - Orchard.Blogs - Edit Blog says New Blog in title 

- src/Orchard.Web/Core/Common/Shapes.cs
When overriding the Parts.Common.Metadata.cshtml in a theme, this will allow for changing the date format used to display the date.
> Allow custom date format when displaying published state

- src/Orchard.Specs/Boolean.feature
- src/Orchard.Specs/Boolean.feature.cs
- src/Orchard.Specs/Enumeration.feature
- src/Orchard.Specs/Enumeration.feature.cs
- src/Orchard.Specs/Input.feature
- src/Orchard.Specs/Input.feature.cs
- src/Orchard.Specs/MediaPicker.feature
- src/Orchard.Specs/MediaPicker.feature.cs
- src/Orchard.Specs/Numeric.feature
- src/Orchard.Specs/Numeric.feature.cs
- src/Orchard.Specs/Text.feature
- src/Orchard.Specs/Text.feature.cs
- src/Orchard.Web/Core/Common/Drivers/TextFieldDriver.cs
- src/Orchard.Web/Modules/Orchard.ContentPicker/Drivers/ContentPickerFieldDriver.cs
- src/Orchard.Web/Modules/Orchard.Fields/Drivers/BooleanFieldDriver.cs
- src/Orchard.Web/Modules/Orchard.Fields/Drivers/DateTimeFieldDriver.cs
- src/Orchard.Web/Modules/Orchard.Fields/Drivers/EnumerationFieldDriver.cs
- src/Orchard.Web/Modules/Orchard.Fields/Drivers/InputFieldDriver.cs
- src/Orchard.Web/Modules/Orchard.Fields/Drivers/LinkFieldDriver.cs
- src/Orchard.Web/Modules/Orchard.Fields/Drivers/NumericFieldDriver.cs
- src/Orchard.Web/Modules/Orchard.MediaLibrary/Drivers/MediaLibraryPickerFieldDriver.cs
- src/Orchard.Web/Modules/Orchard.MediaPicker/Drivers/MediaGalleryFieldDriver.cs
- src/Orchard.Web/Modules/Orchard.MediaPicker/Drivers/MediaPickerFieldDriver.cs
- src/Orchard.Web/Modules/Orchard.Taxonomies/Drivers/TaxonomyFieldDriver.cs
[Fixes #7132] Orchard.Fields - Inconsistent use of mandatory / required
* Fixes inconsistent use of mandatory / required
* Brings wording in line with other validation messages
* Tidies up missing full stops
* Wraps all use of `DisplayName` in `T()`
* Updated specflow tests
> [Fixes #7132] Orchard.Fields - Inconsistent use of mandatory / required

- src/Orchard.Web/Modules/Orchard.DynamicForms/Drivers/CheckboxElementDriver.cs
- src/Orchard.Web/Modules/Orchard.DynamicForms/Drivers/EmailFieldElementDriver.cs
- src/Orchard.Web/Modules/Orchard.DynamicForms/Drivers/HiddenFieldElementDriver.cs
- src/Orchard.Web/Modules/Orchard.DynamicForms/Drivers/TextAreaElementDriver.cs
- src/Orchard.Web/Modules/Orchard.DynamicForms/Drivers/TextFieldElementDriver.cs
- src/Orchard.Web/Modules/Orchard.DynamicForms/Drivers/UrlFieldElementDriver.cs
Fixes #7125 tokenized css class left behind in https://github.com/OrchardCMS/Orchard/commit/e29fb90298659a67b58711a64f0c23746817cb06#diff-b9120625318eac9c2ee807d720870f60
> Fixes #7125 tokenized css class left behind

- src/Orchard.Web/Modules/Orchard.Fields/Drivers/DateTimeFieldDriver.cs
- src/Orchard.Web/Modules/Orchard.Fields/Drivers/LinkFieldDriver.cs
- src/Orchard.Web/Modules/Orchard.Fields/Drivers/NumericFieldDriver.cs
- src/Orchard.Web/Modules/Orchard.MediaLibrary/Drivers/MediaLibraryPickerFieldDriver.cs
- src/Orchard.Web/Modules/Orchard.Templates/Drivers/ShapePartDriver.cs
[Fixes #7111] Fields display as "&amp;" instead of "&" in validation error msgs
> [Fixes #7111] Fields display as "&amp;" instead of "&" in validation error msgs

- src/Orchard.Web/Modules/Orchard.DynamicForms/Drivers/HiddenFieldElementDriver.cs
Fixes #7120 - If a Hidden Field is added to a DynamicForm without a Value set then it will crash the front end because of a null value.
> Fixes #7120 Hidden Field in Dynamic Forms causes crash

- src/Orchard.Web/Modules/Orchard.MediaLibrary/Views/Admin/Index.cshtml
[Fixes #7185] Admin Theme - Media Library - File tree shouldn't have bullets
> [Fixes #7185] Admin Theme - Media Library - File tree shouldn't have bullets

- src/Orchard.Web/Modules/Orchard.Tags/Services/TagService.cs
[Fixes #7192] Orchard.Tags - Manage Tags Admin Page Not Alpha Sorted
> [Fixes #7192] Orchard.Tags - Manage Tags Admin Page Not Alpha Sorted

- src/Orchard.Web/Modules/Orchard.MediaLibrary/Styles/orchard-medialibrary-admin.css
- src/Orchard.Web/Modules/Orchard.MediaLibrary/Views/Admin/Index.cshtml
[Fixes #7202] Orchard.MediaLibrary - Wrong css causes txt wrap to fail
> [Fixes #7202] Orchard.MediaLibrary - Wrong css causes txt wrap to fail

- src/Orchard.Web/Modules/Orchard.Taxonomies/Views/Admin/Index.cshtml
[Fixes #7193] Orchard.Taxonomies - Empty taxonomies view needs full stop
> [Fixes #7193] Admin Theme - Orchard.Taxonomies - Empty taxonomies view needs full stop

- src/Orchard.Web/Modules/Orchard.Tags/Views/Parts/TagCloud.cshtml
[Fixes #7170] Add Orchard.Tags.TagsCloud "no data" message
> [Fixes #7170] Add Orchard.Tags.TagsCloud "no data" message

- src/Orchard/ContentManagement/GroupInfo.cs
[Fixes #7155] Orchard.Framework - GroupInfo generates routes with spaces
> [Fixes #7155] Orchard.Framework - GroupInfo generates routes with spaces

- src/Orchard.Web/Modules/Orchard.DesignerTools/Handlers/ShapeTracingSiteSettingsPartHandler.cs
[Fixes #7318] Orchard.DesignerTools - Setting Id not needed anymore
> [Fixes #7318] Orchard.DesignerTools - Setting Id not needed anymore

- src/Orchard.Web/Core/Shapes/CoreShapes.cs
[Fixes #7258] Orchard.Core - Tabbed groupby breaks priority
> [Fixes #7258] Orchard.Core - Tabbed groupby breaks priority

- src/Orchard.Web/Modules/Orchard.Roles/Services/RoleService.cs
[Fixes #7278] Orchard.Roles GetRoles should defer execution
> [Fixes #7278] Orchard.Roles GetRoles should defer execution

- src/Orchard.Web/Modules/Orchard.Widgets/Views/WidgetFiltersControl.cshtml
This change to the view fixes what I pointed out in #7346 by having both controls reside in the same form. I tested this on a local tenant, and it allows having both "filter" options at the same time in query string
> Fixes #7346

- src/Orchard.Web/Modules/TinyMce/Module.txt
Just because `FeatureDependencies` is not an existing section name, it is never parsed in `Module.txt`.
> Little Correction of TinyMce Module.txt

- src/Orchard.Web/Modules/Orchard.PublishLater/Handlers/PublishLaterPartHandler.cs
Added a functionality that will check when a new version is published, if the previews version has a publish later option. If so it will remove it, in order not to override already newly published content.
Link to issue:
https://github.com/OrchardCMS/Orchard/issues/6840
> RemovePublishLaterTaskIfNewerVersionIsPublished

- src/Orchard.Web/Modules/Orchard.ContentPicker/Drivers/ContentPickerFieldLocalizationDriver.cs
- src/Orchard.Web/Modules/Orchard.ContentPicker/Handlers/ContentPickerFieldLocalizationExtensionHandler.cs
- src/Orchard.Web/Modules/Orchard.ContentPicker/Module.txt
- src/Orchard.Web/Modules/Orchard.ContentPicker/Orchard.ContentPicker.csproj
- src/Orchard.Web/Modules/Orchard.ContentPicker/Placement.info
- src/Orchard.Web/Modules/Orchard.ContentPicker/Settings/ContentPickerFieldLocalizationEditorEvents.cs
- src/Orchard.Web/Modules/Orchard.ContentPicker/Settings/ContentPickerFieldLocalizationSettings.cs
- src/Orchard.Web/Modules/Orchard.ContentPicker/Views/DefinitionTemplates/ContentPickerFieldLocalizationSettings.cshtml
- src/Orchard.Web/Modules/Orchard.ContentPicker/Views/EditorTemplates/Fields/ContentPickerLocalization.Edit.cshtml
As per discussion in #7352, in this commit I created a new feature of the Orchard.ContentPicker module to implement the localization options:
- Try to translate the items selected in the ContentPickerField to the culture of the ContentItem we are saving.
- Remove localizable selected items that do not have a localization to the "correct" culture.
- Remove selected items that do not have a LocalizationPart.
- Check whether all selected items have the "correct" culture, and prevent saving if they don't.
- Consider items without LocalizationPart as being of the "wrong" culture.
> Implements ContentPicker localization options discussed in #7352

- src/Orchard/ContentManagement/IHqlCriterion.cs
DateTime value is now parsed to String in ISO 8601 format.
This PR should solve issue #7432.
> Fix for Query Filter on DateTime fields

- src/Orchard.Web/Modules/Orchard.JobsQueue/AdminMenu.cs
Jobs Queue menu item is now visible to site owners only.
> Jobs Queue menu item visibility

- src/Orchard.Web/Modules/Orchard.Projections/Drivers/ProjectionPartDriver.cs
- src/Orchard.Web/Modules/Orchard.Projections/Orchard.Projections.csproj
- src/Orchard.Web/Modules/Orchard.Projections/Services/IProjectionManagerExtension.cs
- src/Orchard.Web/Modules/Orchard.Projections/Services/ProjectionManager.cs
- Defined a new interface IProjectionManagerExtension that inherits from IProjectionManager
- ProjectionManager now implements IProjectionManagerExtension, so we can pass a part to GetCount and GetContentItems with a ContentPart as input parameter
- GetCount and GetContentItems transform the part into a Content token, so you can filter data with informations contained in the Projection itself
I don't know if it could be helpful in every place where GetCount and GetContentItems are called, so I left the other places untouched. Tell me if I have to integrate.
> ProjectionManager Extension

- src/Orchard.Web/Modules/Orchard.OutputCache/Services/DefaultTagCache.cs
> [Fixes: #7462] Orchard.OutputCache - Possible NRE in DefaultTagCache ctor when accessing the WorkContext

- src/Orchard.Web/Modules/Orchard.Azure/Services/FileSystems/AzureFileSystem.cs
Fix for #7472.
By default Azure blob storage uses service version "2009-09-19". mp4 files served with this version have to be fully downloaded to play.
More info can be found here http://blog.thoughtstuff.co.uk/2014/01/streaming-mp4-video-files-in-azure-storage-containers-blob-storage/.
> Fix for mp4 files not streaming from Azure blob

- src/Orchard.Tests/Environment/ShellBuilders/DefaultShellContainerFactoryTests.cs
- src/Orchard/Environment/ShellBuilders/ShellContainerFactory.cs
- src/Orchard/IDependency.cs
Adds support for decorator functionality.
A developer can decorate any interface that is `IDependency` simply by implementing `IDecorator<>`. For example, to decorate `IContentManager`, you'd do the following:
```
public class MyContentManagerDecorator : IContentManager, IDecorator<IContentManager> {
public MyContentManagerDecorator(IContentManager decoratedService) {
// decoratedService will be an implementation of IContentManager other than this one
}
...
}
```
The magic all happens in `ShellContainerFactory`. Changes to the logic in this class:
- `RegisterType` is deferred until all services have been iterated to determine if they have been decorated
- Concrete implementations are then registered as before, but with the addition of being named, and registered `AsSelf()`
- Decorator …
> Adds IDecorator functionality

- src/Orchard/ContentManagement/DefaultHqlQuery.cs
In a previous version of Orchard src we stored locally we improved a lot the performance of queries avoiding the IN operator in Count hql. It had a relevant impact on pagination cause It used queries based on Count.
So I think it is good to share this improvement providing this PR
> Improved performance of Count Hql queries

- src/Orchard.Web/Modules/Orchard.Alias/Implementation/Holder/AliasHolder.cs
- src/Orchard.Web/Modules/Orchard.Alias/Views/Admin/IndexManaged.cshtml
Fixes #6316
@sebastienros i have used a property to get the aliasMaps. In that property im using lock to make sure no other call is updating it at the same moment. If the count is returned as 0 we call IAliasHolderUpdater.Refresh to refresh the map. Please let me know if this approach is not correct and we need to make any adjustments.
The other shape file had an extra column in the Admin/IndexManaged which has now been removed.
> On Import, the modified url only gets updated in AutoroutePart and not as new Alias (Friendly Url)

- src/Orchard.Web/Modules/Orchard.Packaging/AdminMenu.cs
This avoids to build the Gallery menu item in Modules,Themes and Settings if the tenant is not the default one since the permissions doesn't allow the interaction. Avoid inconsistency commented in issue  #6300
> #6300 Avoid inconsistency occured when building Gallery menu items if the tenant is not the default one

- src/Orchard.Web/Modules/Orchard.OutputCache/Controllers/AdminController.cs
- src/Orchard.Web/Modules/Orchard.OutputCache/Filters/OutputCacheFilter.cs
- src/Orchard.Web/Modules/Orchard.OutputCache/Migrations.cs
- src/Orchard.Web/Modules/Orchard.OutputCache/Models/CacheSettings.cs
- src/Orchard.Web/Modules/Orchard.OutputCache/Models/CacheSettingsPart.cs
- src/Orchard.Web/Modules/Orchard.OutputCache/ViewModels/IndexViewModel.cs
- src/Orchard.Web/Modules/Orchard.OutputCache/Views/Admin/Index.cshtml
Introducing inclusive and exclusive modes for the output cache module's vary by query string parameters functionality. Details of the change are described in issue #7498. 
Here's how the change looks on the cache settings page:
I also added a migration to check if an existing installation is already using the vary by query string parameters and adjust the mode setting to ensure it doesn't experience a change in behavior after upgrading. New and existing installations that don't use the feature will be defaulted to exclusive mode.
> Output cache vary by query string modes

- src/Orchard.Web/Modules/Orchard.Recipes/Orchard.Recipes.csproj
- src/Orchard.Web/Modules/Orchard.Recipes/Providers/Executors/RemoveContentDefinitionStep.cs
Add support for removal of content type and part definitions through recipes.
This addresses issue #7515 .
> [Fixes #7515] Add RemoveContentDefinition recipe step

- src/Orchard.Web/Modules/Orchard.Localization/Controllers/AdminController.cs
- src/Orchard.Web/Modules/Orchard.Localization/Drivers/LocalizationPartDriver.cs
- src/Orchard.Web/Modules/Orchard.Localization/Views/EditorTemplates/Parts/Localization.ContentTranslations.Edit.cshtml
- src/Orchard.Web/Modules/Orchard.Localization/Views/Parts/Localization.ContentTranslations.SummaryAdmin.cshtml
- src/Rebracer.xml
This change should prevent the creation of culture duplicates that was caused by having a different "New 
Translation" link between the two views.
fixes #7348
> [fixes #7348]Changed the SummaryAdmin view to have the same "New Translation" link as the Editor view

- src/Orchard.Web/Modules/Orchard.Taxonomies/Services/ITaxonomyService.cs
- src/Orchard.Web/Modules/Orchard.Taxonomies/Services/TaxonomyService.cs
Avoid deleting terms twice just getting the root terms on DeleteTaxonomy method
#7552
> Fix #7552 Avoid deleting terms twice when deleting a taxonomy

- src/Orchard.Web/Core/Scheduling/Services/ScheduledTaskExecutor.cs
In heavy load on TaskExecutor, not persisting the deleted task causes the following error on MySql database
Unexpected row count: 0; expected: 1
at NHibernate.Linq.DefaultQueryProvider.ExecuteQuery(NhLinqExpression nhLinqExpression, IQuery query, NhLinqExpression nhQuery)
at NHibernate.Linq.DefaultQueryProvider.Execute(Expression expression)
at NHibernate.Linq.DefaultQueryProvider.Execute[TResult](Expression expression)
at S22.IMAP.Handlers.IMAPClientTaskHandler.ScheduleNextTask(DateTime date)
at S22.IMAP.Handlers.IMAPClientTaskHandler.Process(ScheduledTaskContext context)
> Fix the error of ScheduledTaskExecutor

- src/Orchard.Web/Modules/Orchard.Setup/Controllers/SetupController.cs
Previously, it picked the description of the first recipe. The problem is
in the View, the recipes will be sorted based on the name resulted in picking up a
wrong description by controller in case recipes are not sorted by default.
> Fix the bug in representing recipe description in Setup

- src/Orchard/ContentManagement/DefaultHqlQuery.cs
Reverts OrchardCMS/Orchard#7501 (see #7554).
`count(distinct x)` is not supported in SqlCE
> Revert "Improved performance of Count Hql queries"

- src/Orchard.Web/Modules/Orchard.Comments/Controllers/CommentController.cs
- src/Orchard.Web/Modules/Orchard.Users/Migrations.cs
- src/Orchard/Data/Migration/Interpreters/DefaultDataMigrationInterpreter.cs
- src/Orchard/Data/Migration/Interpreters/MySqlCommandInterpreter.cs
Orchard 10.1 cannot be installed by default on a MySql database due to having indexes on too long nvarchar columns.
> Fix issue #7570, #5366, #4780 and #4779 

- src/Orchard.Web/Modules/Orchard.OpenId/Controllers/AccountController.cs
- src/Orchard.Web/Modules/Orchard.OpenId/Models/AzureActiveDirectorySettingsPart.cs
- src/Orchard.Web/Modules/Orchard.OpenId/OwinMiddlewares/AzureActiveDirectory.cs
- src/Orchard.Web/Modules/Orchard.OpenId/Views/Account/Logon.cshtml
- src/Orchard.Web/Modules/Orchard.OpenId/Views/EditorTemplates/Parts.AzureActiveDirectorySettings.cshtml
Consider **`returnUrl`** in the **OpenId** actions. Fixes issue #7530
> Consider "returnUrl" in the `OpenId` actions

- src/Orchard/Caching/ICacheManager.cs
Fixed locking mechanizm in `CacheManager.Get(...)` (bug: #7614)
> #7614 Fixed locking cache-key.
