OrchardCMS/Orchard

src/Orchard.Web/Core/Settings/Handlers/SiteSettingsPartHandler.cs, src/Orchard.Web/Core/Settings/Services/SiteService.cs
Added missing timezone data and fixed conflicts.
=> Moving default SiteSettings values to a handler.

src/Orchard/Mvc/ViewEngines/Razor/WebViewPage.cs, src/Orchard/Mvc/ViewPage.cs, src/Orchard/Mvc/ViewUserControl.cs, src/Orchard/UI/Resources/MetaEntry.cs
@Jetski5822 fixed the feedback provided and pushing into 1.x instead of master. 
Original Pull request (https://github.com/OrchardCMS/Orchard/pull/5178): Remove Duplicate code that could be cleanedup for better maintenance.
=> Remove Duplicate code that could be cleanedup for better maintenance.

src/Orchard.Web/Core/Common/Views/CommonMetadataLastModified.cshtml, src/Orchard.Web/Core/Common/Views/Parts.Common.Metadata.SummaryAdmin.cshtml
Adding fallback to owner if VersionModifiedBy is not filled up
=> Adding fallback to owner if VersionModifiedBy is not filled up

src/Orchard.Web/Modules/Orchard.Azure/Services/FileSystems/AzureFileSystem.cs, src/Orchard.Web/Modules/Orchard.Azure/Services/FileSystems/Media/AzureBlobStorageProvider.cs
This is a fix for #4402, and a resubmission of the [original PR](https://orchard.codeplex.com/SourceControl/network/forks/jchenga/orchard/contribution/7864) by **jchenga**
=> Fix null exception in AzureBlobStorageProvider.GetStoragePath

src/Orchard.Web/Modules/Orchard.Blogs/Handlers/BlogPartArchiveHandler.cs
This fixes #4977 to provide the correct blogpost count when publishing a blogpost with the created date set.
=> fixes #4977 Incorrect BlogPartArchive count

src/Orchard.Web/Modules/Orchard.Workflows/Controllers/AdminController.cs
Fixed #5118, #3998 : Adding Workflow Definition name string empty validation.
Fixed #4716, #4367 : Adding Workflow Definition bulk delete.
=> Workflow Definition fixes

src/Orchard.Web/Modules/Orchard.CodeGeneration/CodeGenerationTemplates/ModuleRootWebConfig.txt
=> Fix for issue #5219

src/Orchard.Web/Modules/Orchard.Workflows/Services/WorkflowManager.cs
In WorkflowManager.TriggerEvent(), these lines are duplicated
=> #5234 Duplicate lines in WorkflowManager

src/Orchard.Web/Modules/Orchard.Search/Controllers/MediaController.cs, src/Orchard.Web/Modules/Orchard.Search/Views/Media/MediaItems.cshtml
Fix for issue https://github.com/OrchardCMS/Orchard/issues/5275.  The fix is to return the FolderPath element in the response to the media search request so that the folderPath check in the javascript code succeeds.
=> Mvarblow patch 5275

src/Orchard.Web/Core/Navigation/Views/Admin/Index.cshtml, src/Orchard.Web/Core/Navigation/Views/EditorTemplates/Parts.MenuWidget.Edit.cshtml, src/Orchard.Web/Core/Navigation/Views/EditorTemplates/Parts.Navigation.Menu.Edit.cshtml, src/Orchard.Web/Modules/Orchard.ContentPicker/Views/EditorTemplates/Parts.Navigation.Edit.cshtml, src/Orchard/Mvc/Html/ContentItemExtensions.cs
Rebased on 1.9.x since this is a bug fix.
=> Fixing #5281

src/Orchard.Web/Modules/Orchard.ContentTypes/Views/Admin/EditPlacement.cshtml
To fix this issue https://github.com/OrchardCMS/Orchard/issues/5291
=> fixing placementeditor try/catch block

src/Orchard.Web/Modules/Orchard.ImportExport/Commands/ImportExportCommands.cs
This is for #4937, resubmitting [the original PR](https://orchard.codeplex.com/SourceControl/network/forks/thekaveman/WorkItem21108/contribution/7812)
=> adding 'export file' command for use in Orchard.exe

src/Orchard.Web/Modules/Orchard.Widgets/Filters/WidgetFilter.cs, src/Orchard.Web/Modules/Orchard.Widgets/Orchard.Widgets.csproj, src/Orchard.Web/Modules/Orchard.Widgets/RuleEngine/RuleManager.cs, src/Orchard.Web/Modules/Orchard.Widgets/Services/DefaultLayerEvaluationService.cs, src/Orchard.Web/Modules/Orchard.Widgets/Services/ILayerEvaluationService.cs
This PR was originally https://github.com/OrchardCMS/Orchard/pull/5363, but I created this new PR in order to merge into `dev` as opposed to `1.9.x`
=> Abstract active layer evaluation away from the Widget Filter

src/Orchard.Web/Modules/Orchard.Taxonomies/Views/Fields/TaxonomyField.cshtml
I think this is just an oversight.
=> Remove a excess @ in TaxonomyField.cshtml

src/Orchard.Web/Modules/Orchard.DynamicForms/Web.config
=> Web.config - Dynamic Forms: MVC reference updated to 5.2.3

src/Orchard.Web/Modules/Orchard.Layouts/Web.config
web.config was still referencing 5.1.0.0
=> Web.Config: Orchard Layouts Updating MVC reference to 5.2.3

src/Orchard.Azure/Orchard.Azure.Web/Web.config
=> Update web.config MVC bindings for Azure Cloud Service

src/Orchard/Data/Migration/Schema/SchemaUtils.cs
fix #5464 - adds native support for creating Guid fields
=> Support CreateColumn<Guid>()

src/Orchard.Web/Modules/Orchard.MediaProcessing/Services/ImageProfileManager.cs
Pull request for fixing in branch 1.9.x this issue that was previously fixed in dev branch https://github.com/OrchardCMS/Orchard/pull/5425#event-346781939
=> Issue #5061 GetImageProfileUrl reprocess images obtained through a dynamic profile on every restart 1.9.x pull request

src/Orchard/ContentManagement/XmlHelper.cs
Fixes this issue https://github.com/OrchardCMS/Orchard/issues/5141
=> Issue #5141 Retrieve/Store methods from InfoSet doesn't support char type

src/Orchard.Azure/Orchard.Azure.Web/Web.config
System.Web.Mvc should bind version 5.2.3.0
=> [Fixes #5530] YSOD instead of the set up page in Azure.

src/Orchard.Web/Modules/Orchard.DesignerTools/Views/ShapeTracingTemplates.cshtml, src/Orchard.Web/Modules/Orchard.Indexing/Services/IndexingTaskExecutor.cs
Incorrect indentation format causes code reading difficulties.
=> Correct code indentation format for file IndexingTaskExecutor.cs

src/Orchard.Web/Modules/Orchard.AntiSpam/Drivers/ReCaptchaPartDriver.cs, src/Orchard.Web/Modules/Orchard.AntiSpam/Orchard.AntiSpam.csproj, src/Orchard.Web/Modules/Orchard.AntiSpam/Services/MissingSettingsBanner.cs, src/Orchard.Web/Modules/Orchard.AntiSpam/ViewModels/ReCaptchaPartEditViewModel.cs, src/Orchard.Web/Modules/Orchard.AntiSpam/Views/EditorTemplates/Parts.ReCaptcha.Fields.cshtml, src/Orchard.Web/Modules/Orchard.DynamicForms/Orchard.DynamicForms.csproj, src/Orchard.Web/Modules/Orchard.DynamicForms/Validators/ReCaptchaValidator.cs, src/Orchard.Web/Modules/Orchard.DynamicForms/ViewModels/ReCaptchaElementViewModel.cs, src/Orchard.Web/Modules/Orchard.DynamicForms/Views/Elements/ReCaptcha.cshtml
=> Issue #5331 - Update Google Recaptcha API

src/Orchard/Mvc/Html/ContentItemExtensions.cs
ItemEditLink may have HTML attributes added - e.g. class.
=> ItemEditLink with Html Attributes

src/Orchard/Data/Migration/Interpreters/DefaultDataMigrationInterpreter.cs
Remove incorrect plus characters that break the compilation
=> Incorrect plus characters break the compilation in DefaultDataMigrationInterpreter.cs

README.md
Was listing 1.8.1 as latest version in the readme. Minor update.
=> Updated README.md Orchard version to 1.9.1

src/Orchard.Web/Modules/Orchard.AntiSpam/Views/EditorTemplates/Parts.ReCaptcha.Fields.cshtml, src/Orchard.Web/Modules/Orchard.DynamicForms/Views/Elements/ReCaptcha.cshtml
This contains the remaining bug fixes for the update to Google ReCaptcha in Orchard. The update was merged in issues 5331 and 5332.
=> Issue #5572 - Bug fixes for Google ReCaptcha 2.0 update

src/Orchard.Web/Modules/Orchard.Widgets/Controllers/AdminController.cs
=> Show Default layer by default in Widgets admin

src/Orchard.Web/Modules/Orchard.Themes/Drivers/DisableThemePartDriver.cs
Added check to not disable the admin theme.
=> Fixes #5693 - DisableTheme Part breaks admin theme

src/Orchard/Mvc/Html/ContentItemExtensions.cs
=> Support htmlAttributes in ItemEditLink

src/Orchard/Environment/DefaultOrchardHost.cs
Fixed #5140 Recipe from Migrations didn't work 
Please review the related issue https://github.com/OrchardCMS/Orchard/issues/5140 to have an explanation of the reason why I have chosen this solution.
=> Fixed #5140 Recipe from Migrations didn't work

src/Gulpfile.js, src/Orchard.Tests/Localization/DefaultDateFormatterTests.cs, src/Orchard.Web/Modules/Orchard.Azure.MediaServices/Models/Assets/EncoderMetadata/AssetFile.cs, src/Orchard.Web/Modules/Orchard.Azure.MediaServices/Models/Assets/EncoderMetadata/Metadata.cs, src/Orchard.Web/Modules/Orchard.Localization/Providers/LocalizationDateTimeFormatProvider.cs, src/Orchard/Localization/Services/CultureDateTimeFormatProvider.cs, src/Orchard/Localization/Services/DefaultDateFormatter.cs, src/Orchard/Localization/Services/IDateTimeFormatProvider.cs
context.Request.HttpMethod fails if context IsBackgroundContext
#5711
=> fix an exception in orchard.exe due to culture selection 

src/Orchard.Web/Modules/Orchard.Workflows/Helpers/OutcomeSerializerExtensions.cs
=> Fix user defined outcome connections in Branching activities

src/Orchard.Web/Modules/Orchard.Workflows/Controllers/AdminController.cs, src/Orchard.Web/Modules/Orchard.Workflows/Models/ActivityRecord.cs, src/Orchard.Web/Modules/Orchard.Workflows/Views/Admin/Edit.cshtml
Update AwaitingActivities after saving a Workflow definition.
Fix for #4352
=> fixes #4352 : orphaned awaitingactivities

src/Orchard/Environment/ShellBuilders/CompositionStrategy.cs
Fixes #5715 
I've done it in the dev branch because the auto-enabling feature isn't present in the 1.9.x branch
=> #5715: Feature key checking in CompositionStrategy

src/Orchard.Web/Modules/Orchard.DynamicForms/Module.txt
The CustomForms module name and website were listed.
=> Updating DynamicForms Module.txt

src/Gulpfile.js, src/Package.json
Will restart the watch task when Assets.json is changed.
=> Enables gulp watch of Assets.json

src/Orchard.Web/Core/Shapes/DateTimeShapes.cs
The implementation was not relative for span further than a week.
=> Improving DateTimeRelative shape

src/Orchard.Web/Modules/Orchard.ContentPicker/Fields/ContentPickerField.cs
Prevents ContentPickerField's ContentItems property from returning null value.
=> Fixes #5614 : ContentPickerField and LayoutPart issue

src/Orchard.sln
This fixed the build on my configuration, possibly related to additional tools like rebraces - which are not installed in my VS.
Order of projects change in sln - csprojs come before rebracer and gulp
=> Possible fix for #5754

src/Orchard/Utility/Extensions/StringExtensions.cs
Made it more obvious how CamelFriendly was choosing to enter spaces in a string
Done on behalf of Radio Systems Corporation
=> Updated StringExtension.cs - CamelFriendly method

src/Orchard.Web/Modules/Orchard.Fields/Views/EditorTemplates/Fields/Enumeration.Edit.cshtml, src/Orchard.Web/Modules/Orchard.Fields/Views/EditorTemplates/Fields/Numeric.Edit.cshtml
=> fixes #3404 : Added Required attribute to Enumeration and Numeric Fields

src/Orchard.Web/Modules/Orchard.AntiSpam/Controllers/AdminController.cs, src/Orchard.Web/Modules/Orchard.AntiSpam/Drivers/SpamFilterPartDriver.cs, src/Orchard.Web/Modules/Orchard.AntiSpam/Handlers/SpamFilterPartHandler.cs, src/Orchard.Web/Modules/Orchard.AntiSpam/Services/DefaultSpamService.cs
This is a pull request that was originally put forward on codeplex and closed in the migration. I've finally gotten around to re submitting it on github. This request is for work item here https://orchard.codeplex.com/workitem/20377
The original pull request also includes a lot of discussion that should be considered.
https://orchard.codeplex.com/SourceControl/network/forks/mjy78/Issue20377/contribution/5915#!/tab/comments
Fixes #4206
=> Issue 20377 - Ensure comment tokens available to antispam module.

src/Orchard.Web/Modules/Orchard.Taxonomies/Services/TermCountProcessor.cs
Removed an unused field and unused using statements.
=> Code clean-up in TermCountProcessor.cs

src/Orchard.Web/Modules/Orchard.OutputCache/Handlers/CacheSettingsPartHandler.cs
=> Implemented output cache routes import/export.

src/Orchard.Web/Config/HostComponents.config, src/Orchard.Web/Modules/Orchard.ImportExport/Providers/ImportActions/ExecuteRecipeAction.cs, src/Orchard.Web/Modules/Orchard.Setup/Controllers/SetupController.cs, src/Orchard/Environment/ShellBuilders/ShellContainerFactory.cs
* Added RecipeExecutionTimeout to SetupController.
* Added RecipeExecutionTimeout to ExecuteRecipeAction.
* Added property-injection registration source to ShellContainerFactory so that controllers can have their public properties be configured.
=> Added configurable RecipeExecutionTimeout properties.

src/Orchard.Web/Modules/Orchard.Comments/Drivers/CommentPartDriver.cs
=> #5836 Fix null ref exception in CommentPartDriver

src/Orchard.Web/Core/Shapes/Scripts/base.js, src/Orchard.Web/Modules/Orchard.ContentTypes/Views/Admin/EditPlacement.cshtml, src/Orchard.Web/Themes/TheAdmin/Scripts/admin.js, src/Orchard.Web/Themes/TheAdmin/Views/Layout.cshtml
Fixes incorrect message with restore placements feature:
Closes #5826
=> Restore placements confirmation message fix

src/Orchard.Web/Modules/Orchard.Layouts/AdminMenu.cs, src/Orchard.Web/Modules/Orchard.Layouts/Controllers/BlueprintAdminController.cs, src/Orchard.Web/Modules/Orchard.Layouts/Controllers/ElementController.cs, src/Orchard.Web/Modules/Orchard.Layouts/Controllers/LayoutController.cs, src/Orchard.Web/Modules/Orchard.Layouts/Migrations.cs, src/Orchard.Web/Modules/Orchard.Layouts/Orchard.Layouts.csproj, src/Orchard.Web/Modules/Orchard.Layouts/Permissions.cs
New Manage Layout permission which displays the Layout menu and grants access to Elements creation.
=> Adding ManageLayout permission

src/Orchard.Web/Modules/Orchard.Taxonomies/Controllers/TagsController.cs, src/Orchard.Web/Modules/Orchard.Taxonomies/Drivers/TaxonomyFieldDriver.cs, src/Orchard.Web/Modules/Orchard.Taxonomies/Orchard.Taxonomies.csproj, src/Orchard.Web/Modules/Orchard.Taxonomies/Scripts/admin-taxonomy-tags.js, src/Orchard.Web/Modules/Orchard.Taxonomies/Services/ITaxonomyService.cs, src/Orchard.Web/Modules/Orchard.Taxonomies/Services/TaxonomyService.cs, src/Orchard.Web/Modules/Orchard.Taxonomies/Styles/admin-taxonomy-tags.css, src/Orchard.Web/Modules/Orchard.Taxonomies/ViewModels/Tag.cs, src/Orchard.Web/Modules/Orchard.Taxonomies/ViewModels/TaxonomyFieldViewModel.cs, src/Orchard.Web/Modules/Orchard.Taxonomies/Views/EditorTemplates/Fields/TaxonomyField.Autocomplete.cshtml
=> #4409: Use service for autocomplete enabled taxonomy field and maintain ordering

src/Orchard.Web/Modules/Orchard.Widgets/Services/DefaultLayerEvaluationService.cs
=> Fixes 1+n db call issue

src/Orchard.Web/Modules/Orchard.Tokens/Implementation/Tokenizer.cs, src/Orchard.Web/Modules/Orchard.Tokens/Orchard.Tokens.csproj, src/Orchard.Web/Modules/Orchard.Tokens/Providers/ListTokens.cs, src/Orchard.Web/Modules/Orchard.Tokens/Tests/ListTokenTests.cs, src/Orchard.Web/Modules/Orchard.Tokens/Tests/Orchard.Tokens.Tests.csproj, src/Orchard.Web/Modules/Orchard.Tokens/Tests/TestTokenProvider.cs
=> #3402: Implemented List tokens.

src/Orchard.Web/Modules/Orchard.CustomForms/Drivers/CustomFormPartDriver.cs
Fix for issue raised on codeplex https://orchard.codeplex.com/workitem/21244
Ensure when creating custom form widgets or pages if the underlying content type that the form uses is not draftable and has security to allow it to be anonymously viewed, that a security warning is displayed.
Fixes #5073
=> Issue 21244 - Display warning when insecure custom forms are created

src/Orchard.Specs/Blogs.feature, src/Orchard.Specs/Blogs.feature.cs, src/Orchard.Specs/Pages.feature, src/Orchard.Specs/Pages.feature.cs, src/Orchard.Web/Modules/Orchard.Alias/Implementation/Map/AliasMap.cs, src/Orchard.Web/Modules/Orchard.Autoroute/Drivers/AutoroutePartDriver.cs, src/Orchard.Web/Modules/Orchard.Autoroute/Handlers/AutoroutePartHandler.cs, src/Orchard.Web/Modules/Orchard.Autoroute/Providers/SlugTokens.cs, src/Orchard.Web/Modules/Orchard.Autoroute/Services/AutorouteService.cs, src/Orchard.Web/Modules/Orchard.Autoroute/Services/HomeAliasService.cs, src/Orchard.Web/Modules/Orchard.Autoroute/Services/IHomeAliasService.cs
- Fixes a bug with the HomeAlias service
- Fixes Pages specflow test (by changing the specification)
=> Home Alias fixes for issue #5791

src/Orchard.Web/Modules/Orchard.Taxonomies/Handlers/TermsPartHandler.cs, src/Orchard.Web/Modules/Orchard.Taxonomies/Services/ITermCountProcessor.cs, src/Orchard.Web/Modules/Orchard.Taxonomies/Services/TaxonomyService.cs, src/Orchard.Web/Modules/Orchard.Taxonomies/Services/TermCountProcessor.cs
Improves, but does not fully resolve, the performance problems described in issue #5663.
=> Prevent no-op tasks for taxonomy field updates.

src/Orchard.Web/Modules/Orchard.Templates/AdminMenu.cs, src/Orchard.Web/Modules/Orchard.Templates/Controllers/AdminController.cs, src/Orchard.Web/Modules/Orchard.Templates/Orchard.Templates.csproj, src/Orchard.Web/Modules/Orchard.Templates/Permissions.cs
=> Adding ManageTemplates permission.

src/Orchard.Web/Modules/Orchard.MediaLibrary/Controllers/AdminController.cs, src/Orchard.Web/Modules/Orchard.MediaLibrary/Scripts/media-library.js, src/Orchard.Web/Modules/Orchard.MediaLibrary/Styles/orchard-medialibrary-admin.css
Added multiple fixes to the media library module:
Fixes infinite count on media library admin view
Fixes issue where Recents link in media library admin view would cause a server error
Fixes minor issue where loading GIF is not really visible when loading more items on scroll
=> Fixes issued #5936 #5938 #5941 and #5891

src/Orchard.Web/Modules/Orchard.MultiTenancy/Scripts/multi-tenancy.admin.js, src/Orchard.Web/Modules/Orchard.MultiTenancy/Views/Admin/Add.cshtml, src/Orchard.Web/Modules/Orchard.MultiTenancy/Views/Admin/Edit.cshtml
took inspiration from technique used in Orchard.Setup module
=> fix multitenancy ui glitch - fixes #5913

src/Orchard.Web/Modules/Orchard.Azure/Services/FileSystems/AzureFileSystem.cs
Needs verification that this will not break anything else - don't think it will.
=> Fixes #5896 - AzureFileStorageProvider

src/Orchard.Web/Modules/Orchard.Modules/styles/orchard-modules-admin.css
=> fix triple columns not fitting on small screens

src/Orchard.Web/Modules/Orchard.Taxonomies/Scripts/admin-taxonomy-tags.js
Fixes #5962. Add any tags that are no longer selected but were initially on page load.
=> Fix for #5962

README.md
Updates:
* had the wrong version listed
* was missing the azure and gitter section at the top
* was still talking about the project in the context of a v1 release
* had duplicated content (how to contribute paragraph + how to get involved section)
* had many out of date links
**NOTE:** If this is accepted I will create additional pull requests for the 1.9.x and dev branches.
=> revamp readme.md and update version to 1.9.2

src/Orchard.Tests/Environment/Loaders/DynamicExtensionLoaderTests.cs, src/Orchard.Web/Modules/Orchard.Redis/Extensions/RedisConnectionExtensions.cs, src/Orchard.Web/Web.config, src/Orchard/Environment/Configuration/ExtensionLocations.cs, src/Orchard/Environment/Extensions/ExtensionMonitoringCoordinator.cs, src/Orchard/Environment/Extensions/Loaders/DynamicExtensionLoader.cs, src/Orchard/Environment/Extensions/Loaders/RawThemeExtensionLoader.cs, src/Orchard/Environment/Extensions/Models/ExtensionDescriptor.cs, src/Orchard/Environment/OrchardStarter.cs, src/Orchard/FileSystems/Dependencies/DynamicModuleVirtualPathProvider.cs, src/Orchard/Localization/Services/DefaultLocalizedStringManager.cs, src/Orchard/Mvc/ViewEngines/IViewEngineProvider.cs, src/Orchard/Mvc/ViewEngines/Razor/RazorViewEngineProvider.cs, src/Orchard/Mvc/ViewEngines/Razor/WebViewPage.cs, src/Orchard/Mvc/ViewEngines/ThemeAwareness/ThemeAwareViewEngine.cs, src/Orchard/Orchard.Framework.csproj
Commit from squashed 1.9.x applied to dev and conflict resolution performed.
intended to resolve #5019, #5241, #5354
=> Ibn labs/additional module directories dev 5

src/Orchard.Web/Core/Navigation/Controllers/AdminController.cs
=> Fires Updating and Updated events when menu items are re-ordered

src/Orchard.Web/Modules/Orchard.Indexing/Commands/IndexingCommands.cs
=> Fixed typo in IndexingCommands.cs

src/Orchard.Web/Modules/Orchard.Tokens/Providers/TextTokens.cs, src/Orchard.Web/Modules/Orchard.Tokens/Tests/Orchard.Tokens.Tests.csproj, src/Orchard.Web/Modules/Orchard.Tokens/Tests/TextTokenTests.cs
This fixes the Format and TrimEnd tokens and adds unit tests for all TextTokens.
=> Fix TextTokens - Format and TrimEnd

src/Orchard/Mvc/ViewEngines/Razor/WebViewPage.cs
fixes #6052 by making Href return the url path as-is if it starts with http or https
=> Fixing the issue no. 6052

src/Orchard.Web/Modules/Orchard.MediaProcessing/Handlers/ImageProfilePartHandler.cs, src/Orchard.Web/Modules/Orchard.MediaProcessing/Services/ImageProfileService.cs
=> Added signal to invalidate media profile cache when newly published.

src/Orchard/ContentManagement/ContentItem.cs
Adding dynamic Content property to the Content Item class for easily acessing Parts and Fields. Thanks Sébastien! :)
=> Adding dynamic Content property to the Content Item class

src/Orchard/Mvc/MvcModule.cs
This reverts commit 9b91b1b2609439bb50dfc0321e72e5f39a95022f.
=> Fixes #6033 : EmailActivity fails when run via background task

src/Orchard.Web/Modules/Orchard.DesignerTools/Services/ShapeTracingFactory.cs
Original fix from @jchenga , pushed on Codeplex but never applied.
=> Fixes #4622 : ShapeTracingFactory Should Not be Activable w/o HttpContext

src/Orchard.Web/Modules/Orchard.MediaProcessing/Handlers/ImageProfilePartHandler.cs
Since this commit https://github.com/OrchardCMS/Orchard/commit/0da937029609557ad3b4223e7f6a0b3a78fa8e30 each time you publish a content item, some errors are logged
Best
=> Errors logged on content item published since a recent commit

src/Orchard.Web/Modules/Orchard.MediaProcessing/Services/IImageProfileManager.cs, src/Orchard.Web/Modules/Orchard.MediaProcessing/Services/ImageProfileManager.cs
=> #6091: ImageProfileManager.GetImageProfileUrl can take multiple customFilters at a time.

src/Orchard.Web/Modules/Orchard.Layouts/Views/EditorTemplates/LayoutEditor.cshtml
Wait for document ready before calling LayoutEditor constructor
Fix for issue https://github.com/OrchardCMS/Orchard/issues/6142
=> Fix for issue #6142

.gitignore
Changed the .gitignore so all /lib dependencies are included correctly.
=> All /lib dll files are now correctly taken into account when using git

src/Orchard.Web/Modules/Orchard.MediaLibrary/Drivers/MediaLibraryPickerFieldDriver.cs
=> Use Display Name to show validation messages

src/Orchard.Web/Modules/Orchard.Resources/Assets.json
second time to fix #6245 in this new branch
=> second time to fix #6245

src/Orchard/Environment/WorkContextAccessor.cs, src/Orchard/Environment/WorkContextModule.cs, src/Orchard/IWorkContextAccessor.cs, src/Orchard/Mvc/HttpContextAccessor.cs, src/Orchard/Tasks/BackgroundService.cs, src/Orchard/WorkContextExtensions.cs
Do exactly the same but provides better clarity.
Best
=> WorkContext & HttpContext: Unused registration and last minor refactoring for better clarity

src/Orchard.Web/Modules/Orchard.ContentPicker/Views/ContentPicker.Edit.cshtml
=> Update ContentPicker.Edit.cshtml link

src/Orchard/ContentManagement/DefaultContentManager.cs
=> Changed the way Handlers are invoked in Export and Import

src/Orchard.Web/Modules/Orchard.Packaging/DefaultPackagingUpdater.cs
=> Updated feed URL for Orchard gallery.

src/Orchard/Services/ClientHostAddressAccessor.cs
=> Check for Nullability of HttpContext while getting Client IP

src/Orchard.Web/Modules/Orchard.ContentPicker/Module.txt, src/Orchard.Web/Modules/Orchard.CustomForms/Module.txt, src/Orchard.Web/Modules/Orchard.Fields/Module.txt, src/Orchard.Web/Modules/Orchard.Forms/Module.txt, src/Orchard.Web/Modules/Orchard.Projections/Module.txt, src/Orchard.Web/Modules/Orchard.Rules/Module.txt, src/Orchard.Web/Modules/Orchard.TaskLease/Module.txt, src/Orchard.Web/Modules/Orchard.Tokens/Module.txt
Fixes #6306
Updated Obsolete codeplex url to the github url in "Module.txt"
=> #6306: Updated codeplex url with github url in modules

src/Orchard.Web/Modules/Orchard.Resources/jQuery.cs
=>  #6354: delete one duplicate definition of script for jQueryUI for orchard 1.10

src/Orchard.Web/Modules/Orchard.MediaProcessing/Services/ImageProfileManager.cs
=> fix #6343 and #6231

src/Orchard.Web/Modules/Orchard.Tags/ResourceManifest.cs, src/Orchard.Web/Modules/Orchard.Tokens/Views/TokenHint.cshtml
=> fix #6374 for 1.10

src/Orchard/Localization/Services/LocalizationStreamParser.cs
=> Add empty scope for localization string without scope

src/Orchard.Web/Modules/Orchard.OutputCache/Filters/OutputCacheFilter.cs, src/Orchard.Web/Modules/Orchard.OutputCache/Views/Admin/Index.cshtml
Fixes #6304 (maybe not completely but at least the main drawback)
New hint texts have been provided to me by @DanielStolt.
Best
=> #6304: Prevents client cache from being disabled when public caching

src/Orchard.Web/Modules/Orchard.Taxonomies/Controllers/TermAdminController.cs
fixes #6400 - improve notifier messages for terms admin
=> fixes #6400 - improve notifier messages for terms admin

src/Orchard.Web/Modules/Orchard.Taxonomies/Controllers/AdminController.cs
fixes #6423 - wrong permission checked for delete
=> fixes #6423 - wrong permission checked for delete

src/Orchard.Web/Modules/Orchard.Widgets/RuleEngine/RuleManager.cs
fix typo in Orchard.Widgets.RuleEngine.cs
=> fix typo in Orchard.Widgets.RuleEngine.cs

src/Orchard.Web/Modules/Orchard.DynamicForms/Drivers/CheckboxElementDriver.cs, src/Orchard.Web/Modules/Orchard.DynamicForms/ValidationRules/Mandatory.cs
fixes #5708 - change ui layer to display mandatory checkbox as required for consistency with other form validators
=> fixes #5708 - change ui layer to display mandatory checkbox as required

src/Orchard.Web/Modules/Orchard.Layouts/Providers/SnippetElementHarvester.cs, src/Orchard.Web/Modules/Orchard.Layouts/Views/Elements/Snippet.Design.cshtml
=> Improved snippets harvester.

src/Orchard.Web/Modules/Orchard.CodeGeneration/CodeGenerationTemplates/ModuleCsProj.txt, src/Orchard.Web/Modules/Orchard.CodeGeneration/CodeGenerationTemplates/ModuleRootWebConfig.txt, src/Orchard.Web/Modules/Orchard.CodeGeneration/CodeGenerationTemplates/ModuleTestsCsProj.txt
Updated codegen templates to resolve issue #6411
=> [Fixes #6411]  Theme code generation produces an 'out-of-date' project

src/Orchard.Web/Modules/Orchard.MediaLibrary/Views/Admin/Index.cshtml, src/Orchard.Web/Modules/Orchard.MediaLibrary/Views/OEmbed/Index.cshtml, src/Orchard.Web/Modules/Orchard.MediaLibrary/Views/Parts/MediaLibrary.Navigation.cshtml, src/Orchard.Web/Modules/Orchard.MediaLibrary/Views/WebSearch/Index.cshtml
Also includes fix for #6396 in 1.10
=> [Fixes #6451] Broken media library font awesome icons

src/Orchard.Web/Modules/Orchard.Users/Views/Admin/Index.cshtml
Fixes issue #6440.  Only display last login or created date for users when there is a value to display
=> [Fixes #6440] Last Login and Created Date

src/Orchard.Web/Modules/Orchard.ContentPicker/Module.txt, src/Orchard.Web/Modules/Orchard.CustomForms/Module.txt, src/Orchard.Web/Modules/Orchard.Fields/Module.txt, src/Orchard.Web/Modules/Orchard.Forms/Module.txt, src/Orchard.Web/Modules/Orchard.Projections/Module.txt, src/Orchard.Web/Modules/Orchard.Rules/Module.txt, src/Orchard.Web/Modules/Orchard.TaskLease/Module.txt, src/Orchard.Web/Modules/Orchard.Tokens/Module.txt
Changed extension manifests to use “orchardproject.net” as the Website
=> fix for #6330

src/Orchard/Environment/State/ContextState.cs
Ending this discussion https://github.com/OrchardCMS/Orchard/commit/42e71fe9fa2cc5337eb9239d68a08a2b680f3df2#commitcomment-16323433 with @DanielStolt and @sfmskywalker, here a last compromise to try that is, as said by sipke, basically the same as it is now...
- Still use the `HttpContext` during a web request because this is more reliable.
- Use the new `IsBackgroundHttpContext()` extension to check if it's a valid context.
- Nevertheless, replace `CallContext.Get/SetData()` with `CallContext.LogicalGet/SetData()`.
- (The last point is easy to revert if some drawbacks)
Best
=> ContextState Compromise

src/Orchard/Environment/State/ContextState.cs
Sorry for the downside of #6492.
=> ContextState: Attempt to fix cross app domain issues on teamcity

src/Orchard.Web/Modules/Orchard.Conditions/Web.config, src/Orchard.Web/Modules/Orchard.Resources/Web.config, src/Orchard/Environment/State/ContextState.cs
@sebastienros, @sfmskywalker 
I've run a normal setup, and through the command line. I'm currently running specflows, seems to be ok, I will tell you when they will be finished.
Best.
=> ContextState: Attempt to fix specflows on teamcity

src/Orchard.Web/Modules/Orchard.Comments/Views/Admin/Details.cshtml, src/Orchard.Web/Modules/Orchard.Comments/Views/Admin/Index.cshtml, src/Orchard.Web/Modules/Orchard.Comments/Views/EditorTemplates/Parts.Comment.AdminEdit.cshtml
Need to alter comment detail page as well.
Comment details on post styled (mostly)
=> Comments module index page layout

src/Orchard.Web/Modules/Orchard.MultiTenancy/Controllers/AdminController.cs
=> fixed one of URL prefix and Host should be required

src/Orchard.Web/Modules/Orchard.Taxonomies/Controllers/TermAdminController.cs
fix wrong permission check and incorrect use of taxonomies phrase
=> fix wrong permission check and incorrect use of taxonomies phrase

src/Orchard.Web/Modules/Orchard.Projections/FilterEditors/Forms/DateTimeFilterForm.cs, src/Orchard.Web/Modules/Orchard.Projections/FilterEditors/Forms/NumericFilterForm.cs
Fixes #6272 update wording for comparisons
=> Fixes #6272 update wording for comparisons

src/Orchard.Web/Modules/Orchard.ContentTypes/Services/ContentDefinitionService.cs
=> 1.10 Field names duplicated in dropdown list, fixed #6497

src/Orchard.Web/Modules/Orchard.OutputCache/Filters/OutputCacheFilter.cs
retargeting of PR #6557 to 1.9.x
=> Output cache route config fixes #6523

src/Orchard.Web/Modules/Orchard.Lists/Shapes.cs, src/Orchard.Web/Modules/Orchard.Lists/Views/Admin/List.cshtml
Fixes #6544
Replace #6545 to target 1.9.x
I also fix a little 404 not found because nprogress.min.css doesn't exist.
=> #6544: NRE with containable part & Orchard.Lists - Replace #6545 to target 1.9.x

src/Orchard.Web/Modules/Orchard.Taxonomies/Drivers/TaxonomyFieldDriver.cs
=> Issue #6572: Add only existing terms for the field.

src/Orchard.Web/Modules/Orchard.Taxonomies/Controllers/TermAdminController.cs, src/Orchard/Environment/DefaultOrchardHost.cs
Just to be able to build the solution.
=> Fixes 1.10.x compilation errors

src/Orchard.Web/Modules/Orchard.Workflows/Activities/TimerActivity.cs
=> fixed Timer activity throws null error exception for 1.10.x

src/Orchard/Environment/DefaultOrchardHost.cs, src/Orchard/Orchard.Framework.csproj, src/Orchard/Utility/NamedReaderWriterLock.cs
=> Block requests to tenant while it's being restarted

src/Orchard.Web/Web.config
=> deleted a duplicated declared Newtonsoft.Json 

src/Orchard.Web/Modules/Orchard.Resources/jQuery.cs
=> fixed min and debug css menifest

src/Orchard.Web/Modules/Orchard.Alias/AdminMenu.cs
Fixes #6651 
Fixes #6219 
Just to fix these issues, as already done in dev a0b66bc by @dcinzona.
Best
=> #6651: [1.10.x] Admin missing menu.aliases-admin.css

src/Orchard.Web/Modules/Orchard.MediaLibrary/Controllers/AdminController.cs
Media Library clone function now uses _mediaLibraryService.GetUniqueFilename() so that we can create clones and also clones of clones ...
Refresh of list after cloning a media item.
Adding MimeType and FolderPath to the media item.
Reformating code to K&R.
fixes #6512
Those 2 are now happy Orchard apples eaters :)
=> #6512: [1.10.x] Media Library: multiple cloning of the same item

src/Orchard.Web/Modules/Orchard.Resources/Module.txt
=> Adding Priority to Orchard.Resources manifest.

src/Orchard.Web/Modules/Orchard.Users/Activities/SignInUserActivity.cs, src/Orchard/Security/Providers/FormsAuthenticationService.cs
This PR fixes this issue https://github.com/OrchardCMS/Orchard/issues/6712
=> #6712 Sign In Workflow Activity fails

src/Orchard.Web/Modules/Orchard.DynamicForms/Drivers/RadioButtonElementDriver.cs, src/Orchard.Web/Modules/Orchard.DynamicForms/Elements/RadioButton.cs, src/Orchard.Web/Modules/Orchard.DynamicForms/Views/Elements/RadioButton.Design.cshtml, src/Orchard.Web/Modules/Orchard.DynamicForms/Views/Elements/RadioButton.cshtml
Furthermore it fixes a bug that makes that after a postback a checked radio button is rendered as unchecked.
Related triage comments to this pull request by Comitte on original pull request https://github.com/OrchardCMS/Orchard/pull/6693
=> #6691 Adds default value for radio button elements

src/Orchard.Web/Modules/Orchard.Fields/Views/EditorTemplates/Fields/Link.Edit.cshtml
Fixes OrchardCMS/Orchard#6736
Originally under PR #6743, but accidently targeted the dev branch, and not 1.10.x
=> Added TextPlaceholder for textbox

src/Orchard.Web/Modules/Orchard.Azure.MediaServices/Views/CloudVideo.Edit.Assets.cshtml, src/Orchard.Web/Modules/Orchard.Azure.MediaServices/Views/CloudVideoPlayer.cshtml, src/Orchard.Web/Modules/Orchard.Azure.MediaServices/Views/Job/Create.cshtml, src/Orchard.Web/Modules/Orchard.Azure.MediaServices/Views/Settings/Index.cshtml
=> fixed JQuery typo

src/Orchard.Web/Modules/Orchard.Layouts/Drivers/BlockquoteElementDriver.cs, src/Orchard.Web/Modules/Orchard.Layouts/Elements/Blockquote.cs, src/Orchard.Web/Modules/Orchard.Layouts/Orchard.Layouts.csproj, src/Orchard.Web/Modules/Orchard.Layouts/ViewModels/BlockquoteEditorViewModel.cs, src/Orchard.Web/Modules/Orchard.Layouts/Views/EditorTemplates/Elements.Blockquote.cshtml, src/Orchard.Web/Modules/Orchard.Layouts/Views/Elements/Blockquote.Design.cshtml, src/Orchard.Web/Modules/Orchard.Layouts/Views/Elements/Blockquote.cshtml, src/Orchard.Web/Orchard.Web.csproj
For issue #6772
This adds a **Blockquote** element to the toolbox, making it awesome for users to add beautifully styled block quote elements to their page.
=> Added Blockquote element

src/Orchard.Web/Modules/Orchard.OutputCache/Filters/OutputCacheFilter.cs
=> fix null etag

src/Orchard.Web/Modules/Orchard.Autoroute/Drivers/AutoroutePartDriver.cs
=> Export the correct AutoroutePart property

src/Orchard/Tasks/Locking/Services/DistributedLockService.cs
=> #6784: [1.10.x] Fixes distributed lock record creation issue if already exists.

src/Orchard.Web/Modules/Orchard.DynamicForms/Views/EditorTemplates/FormBindings.cshtml
It fixes this bug https://github.com/OrchardCMS/Orchard/issues/6842
=> #6842 Element Bindings breaks after adding field to content type

src/Orchard.Tests/UI/Resources/ResourceManagerTests.cs, src/Orchard.Web/Core/Shapes/CoreShapes.cs, src/Orchard/UI/Resources/ResourceDefinition.cs, src/Orchard/UI/Resources/ResourceRequiredContext.cs
This PR supersedes PR #6832 by request from sebastienros to target the dev branch instead of 1.10.x
_(vote here https://github.com/isaacs/github/issues/18 for allowing to change a PR's target branch!)_
=> #6831 Implemented CdnSupportsSsl in Orchard UI Resources (dev)

src/Gulpfile.js, src/Package.json
This adds SASS support to Gulpfile.js.
=> #6860 Added SASS support to Gulpfile.js

src/Orchard.Web/Modules/Orchard.MediaLibrary/Services/MediaLibraryService.cs
Fixes https://github.com/OrchardCMS/Orchard/issues/6856
=> Create target folder if not exist when moving media

src/Orchard.Web/Modules/Orchard.OutputCache/Filters/OutputCacheFilter.cs
One-liner to add the scheme (http/https) to the OutputCacheKey. Fixes #6850.
=> #6850 Added scheme to OutputCacheKey to prevent SSL bypass

src/Gulpfile.js
=> fixes #6865 Add 10 digit precision support to sass

src/Gulpfile.js
=> implement 2nd missing sass pipeline

src/Orchard.sln
This change will help to open solution on linux box.
=> fix path to Orchard.WarmUp - valuable for linux users

src/Orchard/Data/TransactionManager.cs
Fix for database transaction not getting canceled in web api request if there is any exception.
=> Canceling db transaction on exception

src/Orchard.Web/Modules/Orchard.Setup/Scripts/setup.js
fixes #6811 setup recipe description mismatch
=> fixes #6811 setup recipe description mismatch

src/Orchard.Web/Modules/Orchard.Tokens/Filters/TokensFilter.cs, src/Orchard.Web/Modules/Orchard.Tokens/Module.txt
Complement of #6892, related to html filters.
=> Tokens filer execution order & html encode

src/Orchard.Web/Modules/Orchard.Layouts/Elements/Snippet.cs, src/Orchard.Web/Modules/Orchard.Layouts/Providers/SnippetElementHarvester.cs
Retarget of #6914 pr to 1.10.x
=> Fixes #6913 Extend snippet manifest format

src/Orchard.Web/Modules/Orchard.Projections/FilterEditors/Forms/StringFilterForm.cs
solves issue https://github.com/OrchardCMS/Orchard/issues/7003
=> #7003_StringFilterForm

src/Orchard/ContentManagement/IHqlCriterion.cs
=> Orchard.ContentManagement, changed SQL datetime format from ANSI SQL to ISO 8601

src/Orchard.Web/Core/Navigation/Commands/MenuCommands.cs
Control over menu Identity will help in setting menu identifier in menu items from the recipe data.
=> Identity support to menu create command switch

ClickToBuild.cmd, deploy.cmd, src/Orchard.Web/Core/Contents/Views/Admin/List.cshtml, src/Orchard.Web/Themes/TheAdmin/Styles/site.css
=> Admin, content list, fixed lowercase display and CSS class of bulk labels

src/Orchard.Web/Core/Containers/Views/DefinitionTemplates/ContainerTypePartSettingsViewModel.cshtml, src/Orchard.Web/Core/Navigation/Views/EditorTemplates/Parts.MenuWidget.Edit.cshtml, src/Orchard.Web/Modules/Orchard.Azure.MediaServices/Controllers/AssetController.cs, src/Orchard.Web/Modules/Orchard.Azure.MediaServices/Controllers/JobController.cs, src/Orchard.Web/Modules/Orchard.Azure.MediaServices/Controllers/MediaController.cs, src/Orchard.Web/Modules/Orchard.Layouts/Views/EditorTemplates/Elements.Menu.cshtml, src/Orchard.Web/Modules/Orchard.Projections/Providers/Layouts/GridLayoutForms.cs
=> Typo #6902

src/Orchard.Web/Modules/Lucene/Services/LuceneIndexProvider.cs, src/Orchard.Web/Modules/Orchard.Alias/Controllers/AdminController.cs, src/Orchard.Web/Modules/Orchard.AntiSpam/Services/AkismetApiSpamFilter.cs, src/Orchard.Web/Modules/Orchard.Azure/Services/Caching/Output/AzureOutputCacheStorageProvider.cs, src/Orchard.Web/Modules/Orchard.Blogs/Commands/BlogCommands.cs, src/Orchard.Web/Modules/Orchard.CodeGeneration/Commands/CodeGenerationCommands.cs, src/Orchard.Web/Modules/Orchard.Comments/Services/CommentService.cs, src/Orchard.Web/Modules/Orchard.Indexing/Controllers/AdminController.cs, src/Orchard.Web/Modules/Orchard.Indexing/Services/IndexingTaskExecutor.cs, src/Orchard.Web/Modules/Orchard.MediaProcessing/Shapes/MediaShapes.cs, src/Orchard.Web/Modules/Orchard.MessageBus/Brokers/SqlServer/SqlServerBroker.cs, src/Orchard.Web/Modules/Orchard.MessageBus/Brokers/SqlServer/Worker.cs, src/Orchard.Web/Modules/Orchard.Migrations/Commands/DataMigrationCommands.cs, src/Orchard.Web/Modules/Orchard.Migrations/Commands/DatabaseUpdateCommands.cs, src/Orchard.Web/Modules/Orchard.Modules/Controllers/AdminController.cs, src/Orchard.Web/Modules/Orchard.OutputCache/Filters/OutputCacheFilter.cs, src/Orchard.Web/Modules/Orchard.Redis/MessageBus/RedisMessageBusBroker.cs, src/Orchard.Web/Modules/Orchard.Setup/Services/SetupService.cs, src/Orchard.Web/Modules/Orchard.Themes/Controllers/AdminController.cs, src/Orchard.Web/Modules/Orchard.Warmup/Services/WebDownloader.cs, src/Orchard/Data/Migration/Schema/SchemaBuilder.cs, src/Orchard/Environment/DefaultOrchardShell.cs, src/Orchard/Exceptions/Filters/UnhandledExceptionFilter.cs, src/Orchard/FileSystems/LockFile/DefaultLockFileManager.cs, src/Orchard/Messaging/Services/DefaultMessageManager.cs
fixed typo flagged up in issue 7076
https://github.com/OrchardCMS/Orchard/issues/7076
=> fix typo of occured for logging messages and notification

src/Orchard.Web/Core/Contents/Views/Content.Summary.cshtml
Small change to Content.Summary.cshtml to allow module developers to add classes to Content.Summary.cshtml via ShapeTableBuilder.Describe.
=> Allow adding HTML classes through ShapeTableBuilder.Describe

src/Orchard.Web/Core/Common/Views/Body-Large.Editor.cshtml, src/Orchard.Web/Core/Common/Views/Body-Small.Editor.cshtml, src/Orchard.Web/Core/Common/Views/Body-Textarea.Editor.cshtml, src/Orchard.Web/Core/Common/Views/Body-Wide.Editor.cshtml, src/Orchard.Web/Core/Common/Views/Body.Editor.cshtml, src/Orchard.Web/Modules/Markdown/Views/Body-Markdown.Editor.cshtml, src/Orchard.Web/Modules/TinyMce/Views/Body-Html.Editor.cshtml
I've made the recommended changes to all available editor types.
=> Fixes #7043: Displaying Multiple Editors from a Custom Part

src/Orchard.Web/Modules/Orchard.Azure/Services/FileSystems/AzureFileSystem.cs
Fixes #7119 Path Comparison Case Sensitivity
=> Fixes #7119 Orchard.Azure Path Comparison Case Sensitivity

src/Orchard.Web/Modules/Orchard.Fields/Views/EditorTemplates/Fields/Boolean.Edit.cshtml
[Fixes #7129] Boolean.cshtml doesn't have * required support in view
=> [Fixes #7129] Boolean.cshtml doesn't have * required support in view

src/Orchard.Web/Themes/TheAdmin/TheAdmin.csproj
If the script snippet is not located in the footer then jQuery will not be recognized.
=> Feature/admin theme Update EditPlacement.cshtml 

src/Orchard.Web/Modules/Orchard.ImageEditor/Styles/orchard-imageeditor-admin.css, src/Orchard.Web/Modules/Orchard.Layouts/Styles/admin-dialog.css, src/Orchard.Web/Themes/SafeMode/Styles/site.css, src/Orchard.Web/Themes/TheAdmin/Styles/site.css
[Fixes #7153] Typo .buton:active in several css files
=> [Fixes #7153] Typo .buton:active in several css files

src/Orchard.Web/Core/Settings/Views/EditorTemplates/Parts.Settings.SiteSettingsPart.cshtml
[Fixes #7151] Orchard.Core - Use CDN setting ui not correct
=> [Fixes #7151] Orchard.Core - Use CDN setting ui not correct

src/Orchard/Environment/DefaultOrchardShell.cs
This wraps owin middleware configuration within a work context scope.
Fixes #6991
=> Wrapped owin middleware config

src/Orchard.Web/Modules/Orchard.Setup/Recipes/blog.recipe.xml
[Fixes #7115] Orchard.Setup blog setup recipe issues
=> [Fixes #7115] Orchard.Setup blog setup recipe issues

src/Orchard.Web/Modules/Orchard.ContentTypes/ViewModels/AddFieldViewModel.cs, src/Orchard.Web/Modules/Orchard.ContentTypes/ViewModels/EditFieldNameViewModel.cs, src/Orchard.Web/Modules/Orchard.ContentTypes/Views/Admin/AddFieldTo.cshtml, src/Orchard.Web/Modules/Orchard.ContentTypes/Views/Admin/Edit.cshtml, src/Orchard.Web/Modules/Orchard.ContentTypes/Views/Admin/EditField.cshtml, src/Orchard.Web/Modules/Orchard.ContentTypes/Views/EditorTemplates/Field.cshtml
[Fixes #7131] Orchard.ContentTypes - Add / Edit Field Issues
=> [Fixes #7131] Orchard.ContentTypes - Add / Edit Field Issues

src/Orchard.Web/Themes/TheAdmin/Views/Layout.cshtml
[Fixes #7187] Admin Theme - Typo On Delete Dialog Confirm Message
=> [Fixes #7187] Admin Theme - Typo On Delete Dialog Confirm Message

src/Orchard.Web/Modules/Orchard.MediaLibrary/Views/Folder/Edit.cshtml
[Fixes #7189] Admin Theme - Media Library - Edit folder wrong button classes and order
=> [Fixes #7189] Admin Theme - Media Library - Edit folder btn order + classes

src/Orchard.Web/Core/Contents/Views/Admin/List.cshtml
[Fixes #7183] Admin Theme - Empty manage page content typo
=> [Fixes #7183] Admin Theme - Empty manage page content typo

src/Orchard.Web/Modules/Orchard.MediaLibrary/Scripts/media-library.js, src/Orchard.Web/Modules/Orchard.MediaLibrary/Views/Admin/Index.cshtml, src/Orchard.Web/Modules/Orchard.MediaLibrary/Views/Parts/Media.Actions.cshtml
[Fixes #7205] Admin Theme - Media Library - Button styles
=> [Fixes #7205] Admin Theme - Media Library - Button styles

src/Orchard.Web/Core/Shapes/Scripts/base.js, src/Orchard.Web/Themes/TheAdmin/Views/Layout.cshtml
[Fixes #7194] Admin Theme - Merge default delete confirm msg feature
=> [Fixes #7194] Admin Theme - Merge default delete confirm msg feature

src/Orchard.Web/Modules/Orchard.Blogs/Placement.info
[Fixes #7171] Orchard.Blogs - Hide Parts_Common_Metadata on blog
=> [Fixes #7171] Orchard.Blogs - Hide Parts_Common_Metadata on blog

src/Orchard/ContentManagement/DefaultContentManager.cs
=> [Fixes #7246] DefaultContentManager - Added missing null checks after Get() calls

src/Orchard.Web/Modules/Orchard.ContentPicker/Styles/content-picker-admin.css, src/Orchard.Web/Modules/Orchard.ContentPicker/Views/EditorTemplates/Parts.ContentMenuItem.Edit.cshtml
[Fixes #7186] Admin Theme - Content Menu Item - Content Picker Edit Button
=> [Fixes #7186] Admin Theme - Content Menu Item - Content Picker Edit Button

src/Orchard.Web/Themes/TheAdmin/Web.config
[Fixes #7243] Admin Theme - web.config compilation targetFramework="4.5.1"
=> [Fixes #7243] Admin Theme - web.config compilation targetFramework="4.5.1"

src/Orchard.Web/Modules/Orchard.Blogs/Views/Parts.Blogs.BlogArchives.cshtml, src/Orchard.Web/Modules/Orchard.Tags/Views/Parts/TagCloud.cshtml
[Fixes #7168, Fixes #7169, Fixes #7170] Blog Recent Posts, Archives, Tag Cloud "no data" msgs
=> [Fixes #7168, #7169, #7170] Blog Recent Posts, Archives, Tag Cloud "no data" msgs

src/Orchard.Web/Modules/Orchard.MediaProcessing/Views/Filter/Edit.cshtml
[Fixes #7271] Admin Theme - Media Profile Edit Filter Form
=> [Fixes #7271] Admin Theme - Media Profile Edit Filter Form

src/Orchard.Web/Modules/Orchard.MediaLibrary/Views/Admin/Index.cshtml
[Fixes #7207] - Admin Theme - Media Library - Typos In Msgs
=> [Fixes #7207] - Admin Theme - Media Library - Typos In Msgs

src/Orchard.Web/Modules/Orchard.Indexing/Services/IndexingTaskExecutor.cs
=> Fixed an issue with incorrect log message at Indexing module

src/Orchard.Web/Modules/Orchard.MultiTenancy/Views/Admin/Add.cshtml, src/Orchard.Web/Modules/Orchard.MultiTenancy/Views/Admin/Edit.cshtml
[Fixes #7301] Orchard.MultiTenancy - Mismatched ConnectionString UI between add/edit
=> [Fixes #7301] Orchard.MultiTenancy - Mismatched ConnectionString UI between add/edit

src/Orchard.Web/Core/Contents/Controllers/AdminController.cs
[Fixes #4723, Fixes #6769] Orchard.Core.Contents - Verify type exists on create content
=> [Fixes #4723, Fixes #6769] Orchard.Core.Contents - Verify type exists on create content

src/Orchard.Web/Modules/Orchard.Layouts/Services/ElementManager.cs
=> Fixed an issue with layout element lookup

src/Orchard/UI/Resources/LinkEntry.cs
[Fixes #5960] LinkEntry needs Sizes Attribute
=> [Fixes #5960] LinkEntry needs Sizes Attribute

src/Orchard.Web/Modules/Orchard.SecureSocketsLayer/Filters/SecureSocketsLayersFilter.cs, src/Orchard.Web/Modules/Orchard.SecureSocketsLayer/Orchard.SecureSocketsLayer.csproj, src/Orchard.Web/Modules/Orchard.SecureSocketsLayer/Services/MissingSettingsBanner.cs
[Fixes #6494] SSL missing settings banner showing on frontend
=> [Fixes #6494] SSL missing settings banner showing on frontend

src/Orchard.Web/Core/Contents/Controllers/AdminController.cs
[Fixes #7297] Orchard.Core - Improve wording of Notifier in Content Management admin
=> [Fixes #7297] Orchard.Core - Improve wording of Notifier in Content Management admin

src/Rebracer.xml
[Fixes #7299] Update defaults for rebracer.xml
=> [Fixes #7299] Update defaults for rebracer.xml

src/Orchard.Web/Modules/Orchard.OutputCache/Handlers/CacheSettingsPartHandler.cs
Fixes: #7255 
OnRemoved and OnDestroyed handlers implemented.
=> Cached items are not evicted on Remove and Destroy

src/Orchard.Web/Modules/Orchard.Widgets/Filters/WidgetFilter.cs
[Fixes #7326] Orchard.Widgets - Fix typo in logger
=> [Fixes #7326] Orchard.Widgets - Fix typo in logger

src/Orchard.Web/Modules/Orchard.Users/Views/Admin/Index.cshtml
[Fixes #7071] Orchard.Users - Users last login time is not correct
=> [Fixes #7071] Orchard.Users - Users last login time is not correct

src/Orchard.Web/Modules/Orchard.Blogs/Commands/BlogWidgetCommands.cs, src/Orchard.Web/Modules/Orchard.Blogs/Orchard.Blogs.csproj, src/Orchard.Web/Modules/Orchard.Blogs/Services/BlogService.cs, src/Orchard.Web/Modules/Orchard.Setup/Recipes/blog.recipe.xml, src/Orchard.Web/Modules/Orchard.Tags/Commands/TagsWidgetCommands.cs, src/Orchard.Web/Modules/Orchard.Tags/Orchard.Tags.csproj
[Fixes #7251, Fixes #1659] Orchard.Setup - Blog recipe doesn't create widgets correctly
=> [Fixes #7251, Fixes #1659] Orchard.Setup - Blog recipe doesn't create widgets correctly

src/Orchard.Web/Modules/Orchard.Blogs/AdminMenu.cs, src/Orchard.Web/Modules/Orchard.Blogs/Orchard.Blogs.csproj, src/Orchard.Web/Modules/Orchard.Blogs/Views/Content-BlogPost.PublishButton.cshtml, src/Orchard.Web/Modules/Orchard.Blogs/Views/Content-BlogPost.SummaryAdmin.cshtml
See #3933, #4767, and #6993 for background.
=> Blogs permission check consistency

src/Orchard.Web/Modules/Orchard.Blogs/Commands/BlogWidgetCommands.cs, src/Orchard.Web/Modules/Orchard.Tags/Commands/TagsWidgetCommands.cs, src/Orchard.Web/Modules/Orchard.Widgets/Commands/WidgetCommands.cs, src/Orchard.Web/Modules/Orchard.Widgets/Orchard.Widgets.csproj, src/Orchard.Web/Modules/Orchard.Widgets/Services/IWidgetCommandsService.cs, src/Orchard.Web/Modules/Orchard.Widgets/Services/WidgetCommandsService.cs
[Fixes #7339] Orchard.Widgets - Refactor #7251
=> [Fixes #7339] Orchard.Widgets - Refactor #7251

src/Orchard.Web/Modules/Orchard.DynamicForms/Drivers/EmailFieldElementDriver.cs, src/Orchard.Web/Modules/Orchard.DynamicForms/Drivers/EnumerationElementDriver.cs, src/Orchard.Web/Modules/Orchard.DynamicForms/Drivers/HiddenFieldElementDriver.cs, src/Orchard.Web/Modules/Orchard.DynamicForms/Drivers/QueryElementDriver.cs, src/Orchard.Web/Modules/Orchard.DynamicForms/Drivers/TaxonomyElementDriver.cs, src/Orchard.Web/Modules/Orchard.DynamicForms/Drivers/TextAreaElementDriver.cs, src/Orchard.Web/Modules/Orchard.DynamicForms/Drivers/TextFieldElementDriver.cs, src/Orchard.Web/Modules/Orchard.DynamicForms/Drivers/UrlFieldElementDriver.cs, src/Orchard.Web/Modules/Orchard.DynamicForms/Elements/Enumeration.cs, src/Orchard.Web/Modules/Orchard.DynamicForms/Elements/Query.cs, src/Orchard.Web/Modules/Orchard.DynamicForms/Elements/Taxonomy.cs
Fixes #6530, fixes #6237 
#6530 is already closed, but for 1.10.x we still need 41e9052 that is only applied to dev.
#6237 is related to dev and still open, but i think it has been fixed after 41e9052.
Here, the copy of 41e9052 but for 1.10.x.
Best
=> #6530: [1.10.x] dyn form field default value tokenization

src/Orchard/Events/EventsInterceptor.cs
EventsInterceptor fails when it tries to locate a generic method on an implementation with a return type. A null check has been added to avoid the exception.
Related issues: #4718, #4584
Related PR: #7337
=> Fix for null exception thrown on null genereic method

src/Orchard.Web/Modules/Orchard.AuditTrail/Services/AuditTrailManager.cs
I've changed the Audit Trail trimming task to delete all records in one batch, rather than iterating through the table records. This will be a far more efficient method of clearing up the audit trail.
I brought in ITransactionManager instead of changing IRepository to support multiple deletions, as this would have less of an impact on the codebase.
=> Changed Audit Trail trimming task to delete all records in one batch

src/Orchard.Web/Modules/Orchard.Localization/Drivers/LocalizationPartDriver.cs, src/Orchard/ContentManagement/DefaultContentManager.cs
Small corrections based on @MatteoPiovanelli-Laser comments on 87a394854dda9a45b36d757b3d3ce135ac18d24d
=> Cloning and Translation fixes

src/Orchard.Web/Modules/Orchard.Taxonomies/Controllers/TermAdminController.cs
TermQuery must be sliced after sorting
=> Fixes #6795 : Sort Taxonomies Terms failed

src/Orchard/Environment/DefaultOrchardShell.cs
This is a proposed fix to the issue #7362
=> Fix  the problem preventing reading SiteSettings from the Routes class

src/Orchard.Web/Modules/Orchard.MultiTenancy/Commands/TenantCommand.cs, src/Orchard.Web/Modules/Orchard.MultiTenancy/Controllers/AdminController.cs
solves issue #7428 and the bug introduced in #7399
=> fixed the string literals in Regex.IsMatch

src/Orchard.Web/Modules/Orchard.ImportExport/Commands/ImportExportCommands.cs, src/Orchard.Web/Modules/Orchard.ImportExport/Providers/ExportActions/BuildRecipeAction.cs, src/Orchard.Web/Modules/Orchard.Recipes/Providers/RecipeHandlers/RecipeExecutionStepHandler.cs, src/Orchard/Orchard.Framework.csproj, src/Orchard/Recipes/Services/IRecipeBuilderStepResolver.cs, src/Orchard/Recipes/Services/IRecipeExecutionStepResolver.cs, src/Orchard/Recipes/Services/RecipeBuilderStepResolver.cs, src/Orchard/Recipes/Services/RecipeExecutionStepResolver.cs
This PR resolves issue raised in [#7441](https://github.com/OrchardCMS/Orchard/issues/7441)
=> Adapt export steps flag to work with refactored steps

src/Orchard.Web/Modules/Orchard.Autoroute/Migrations.cs, src/Orchard.Web/Modules/Orchard.Autoroute/Providers/ContentDefinition/ContentDefinitionEventHandler.cs, src/Orchard.Web/Modules/Orchard.Autoroute/Services/AutorouteService.cs, src/Orchard.Web/Modules/Orchard.Autoroute/Settings/AutorouteSettingsEvents.cs, src/Orchard.Web/Modules/Orchard.Autoroute/Views/DefinitionTemplates/AutorouteSettings.cshtml
Fixed support for localized and culture neutral patterns (issue #7430)
=> Added support for culture neutral patterns

src/Orchard.Web/Modules/Orchard.Taxonomies/AdminMenu.cs, src/Orchard.Web/Modules/Orchard.Taxonomies/Controllers/AdminController.cs, src/Orchard.Web/Modules/Orchard.Taxonomies/Controllers/TermAdminController.cs, src/Orchard.Web/Modules/Orchard.Taxonomies/Handlers/TaxonomyPartHandler.cs, src/Orchard.Web/Modules/Orchard.Taxonomies/Handlers/TermPartHandler.cs, src/Orchard.Web/Modules/Orchard.Taxonomies/Views/Admin/Index.cshtml, src/Orchard.Web/Modules/Orchard.Taxonomies/Views/TermAdmin/Index.cshtml
=> [Fixes #7413] problem with permissions for taxonomies and terms

src/Orchard/Environment/DefaultOrchardHost.cs
Fixes a small issue where tenants that are restarted get stuck in an infinite loop.
=> Fix tenant restart infinite loop.  Fixes #7469

src/Orchard.Web/Modules/Orchard.Fields/Views/EditorTemplates/Fields/Link.Edit.cshtml
As requested by @DanielStolt 
Best.
=> Fixes usage of undeclared variables in Link.Edit.cshtml.

src/Orchard.Web/Modules/Orchard.Pages/Commands/PageCommands.cs
Create layout with a Canvas root element so it can be edited in the Orchard admin.  Fixes https://github.com/OrchardCMS/Orchard/issues/7474.
=> Create editable layout from page create command.

src/Orchard.Web/Modules/Orchard.DesignerTools/Controllers/AlternateController.cs, src/Orchard.Web/Modules/Orchard.DesignerTools/Services/ShapeTracingFactory.cs, src/Orchard.Web/Modules/Orchard.OutputCache/Filters/OutputCacheFilter.cs, src/Orchard.Web/Modules/Orchard.Themes/Services/ThemeService.cs, src/Orchard/Themes/ThemeManager.cs
=> [Fixes #1531] IThemeSelector.GetTheme() gets called several times.

src/Orchard/Data/Migration/AutomaticDataMigrations.cs
=> Removed duplicated line in AutomaticDataMigrations.cs

src/Orchard.Web/Modules/Orchard.ContentTypes/Migrations.cs
fixes public method name #7611
=> [Fixes 7611] Changed UpgradeFrom1 to UpdateFrom1 on Migration of ContentTypes module

src/Orchard/Data/Migration/Interpreters/DefaultDataMigrationInterpreter.cs, src/Orchard/Data/Migration/Interpreters/MySqlCommandInterpreter.cs
The fix checks the length of the field in the db, if it is a string based
field with length bigger than 767, then it provides minimum length for
the field in the index
=> Fix issue #5366, #4780 and #4779 by providing length for indexes

src/Orchard.Web/Modules/Orchard.ContentPicker/Handlers/ContentPickerFieldLocalizationExtensionHandler.cs
=> Allows draft ContentItems in ContentPickerField

src/Orchard.Web/Modules/Orchard.Azure/Constants.cs, src/Orchard.Web/Modules/Orchard.Azure/Module.txt
=>  remove the unused feature names
